multiversx/mx-exchange-service

- src/modules/auth/native.auth.guard.ts
-  the auth.addres was not set to the impersonate address in case of native auth guardian.
- 
- set the auth.addres to the impersonate address 
- query a request guarded by JwtOrNativeAuthGuard. It should now behave as the impersonated address made the request.
> SERVICES-1227: fix native auth impersonate

- src/modules/tokens/services/token.getter.service.ts
- token type refresh time is too big
- lower token type cache ttl
- N/A
> [SERVICES-1404] update token type cache ttl

- src/services/cache.warmer.module.ts
- src/services/crons/cache.warmer.service.ts
- src/services/external-communication/api.cmc.setter.service.ts
- src/services/external-communication/external.communication.module.ts
- external calls to CMC from all API instances
- use cache warmer to pre-warm USDC value in cache
- only 1 request / 2 minutes should be performed to CMC
> [SERVICES-1411] add cache warm for USDC price from CMC

- src/modules/auth/native.auth.guard.ts
- src/utils/url.utils.ts
- empty origin header would result in an error at URL object creation
- add proper error handling for empty origin header
- any authenticated query should work even with missing origin header
> [SERVICES-1455] fix native auth origin header

- src/modules/user/services/userEnergy/user.energy.getter.service.ts
- src/modules/user/services/userEnergy/user.energy.transaction.service.ts
- src/modules/user/user.resolver.ts
- users can't opt out from fees collector rewards
- add option to skip checks for outdated energy on fees collector
- `updateEnergy` transaction should not provide fees collector address if `skipFeesCollector` is true
> [SERVICES-1355] skip fees collector from outdated contracts

- src/modules/energy/services/energy.service.ts
- xmex with no penalty amount returns error on query
- return `0` penalty amount if xmex can be unlocked with no penalty
- `penaltyAmount` query should not throw error if xmex is unlockable
> [SERVICES-1354] xmex no penalty amount

- src/modules/farm/v1.2/services/farm.v1.2.abi.service.ts
- src/modules/farm/v1.3/services/farm.v1.3.abi.service.ts
- base farm abi service did not had mxProxy instance passed from child
- add mxProxy in child constructors for farms versioned abi services
`
farms {
... on FarmModelV1_2 {
address
farmedToken {
identifier
}
}
}
`
query should return values
> [SERVICES-1520] fix farms v1.2 and v1.3 abi services

- src/submodules/week-timekeeping/services/week-timekeeping.abi.service.ts
- weektimekeeping abi service is not injected
- add injectable decorator for abi service
`
farms {...on FarmModelV2 {time {currentWeek}}}
`
query should return value
> [SERVICES-1233] add missing injectable service

- src/modules/escrow/services/escrow.abi.service.ts
- wrong return values
- use BigNumber with base 16 as return values
- query `escrowContract` should return all information
> [SERVICES-1310] fix return values from escrow abi service

- src/modules/pair/services/pair.abi.service.ts
- src/services/crons/pair.cache.warmer.service.ts
- pairs fee percents were cached without denomination
- added denomination for pair fees percents
- `totalFeePercent` and `specialFeePercent` fields from pairs should return values in decimals: `0.003` / `0.0005` / `0.001`
> [SERVICES-1553] fix cached values for pair fees percents

- src/modules/energy/energy.module.ts
- src/modules/fees-collector/fees-collector.module.ts
- src/modules/fees-collector/fees-collector.resolver.ts
- src/modules/fees-collector/services/fees-collector.compute.service.ts
- src/modules/fees-collector/specs/fees-collector.service.spec.ts
- src/modules/fees-collector/specs/fees.collector.compute.service.spec.ts
- src/modules/pair/mocks/pair.constants.ts
- src/modules/pair/services/pair.setter.service.ts
- src/submodules/weekly-rewards-splitting/mocks/weekly.rewards.splitting.abi.mock.ts
- src/submodules/weekly-rewards-splitting/services/weekly-rewards-splitting.compute.service.ts
- src/submodules/weekly-rewards-splitting/specs/weekly-rewards-splitting.compute.service.spec.ts
- compute user fees collector APR based on last week distributed rewards
- fixed total rewards usd compute method from weekly module
- added method to compute user APR for fees collector
- added endpoint to get actual user APR or use new values for energy or locked tokens to simulate new APR values
- query `userLastWeekRewards` should return an APR expressed in percentages with and without the optional arguments
> [SERVICES-1535] user fees collector APR

- src/modules/user/services/user.metaEsdt.service.ts
- on devnet accounts can have metaEsdt tokens that are not tracked anymore
- filter out undefined user metaEsdt tokens
```
query UserNfts {
userNfts {
address
userDualYieldToken {
collection
identifier
valueUSD
decodedAttributes {
lpFarmTokenNonce
lpFarmTokenAmount
stakingFarmTokenNonce
stakingFarmTokenAmount
}
}
}
}
```
> [SERVICES-1590] fix undefined user meta esdts

- src/modules/pair/services/pair.abi.service.ts
- lockedTokensInfo from pair had wrong cache keys
- update generated cache keys for lockedTokensInfo fields
- `lockedTokensInfo` field from `pair` model should not return errors
> [SERVICES-1520] fix wrong cache keys in pair abi service

- src/modules/auth/gql.admin.guard.ts
- src/modules/auth/jwt.or.native.admin.guard.ts
- src/modules/auth/native.admin.guard.ts
- src/modules/energy/energy.resolver.ts
- src/modules/farm/farm.transaction.resolver.ts
- src/modules/pair/pair.resolver.ts
- src/modules/remote-config/remote-config.controller.ts
- src/modules/router/router.resolver.ts
- src/modules/staking/staking.resolver.ts
- src/modules/tokens/token.controller.ts
- Native auth for admins missing
- added native auth guard for admin
- added jwt or native auth guard for admins
- with admin address set, query any endpoint guarded with `JwtOrNativeAdminGuard`. Should work for whitelisted admins and fail for other addresses
> [SERVICES-1602] add native admin guard

- package.json
- src/config/devnet.json
- src/helpers/validators/metric.validator.ts
- src/modules/analytics/analytics.resolver.ts
- src/modules/analytics/models/query.args.ts
- src/modules/farm/models/farm.model.ts
- src/modules/price-discovery/models/price.discovery.args.ts
- src/modules/price-discovery/price.discovery.resolver.ts
- src/modules/price-discovery/services/price.discovery.compute.service.ts
- src/modules/price-discovery/validators/pd.args.validator.ts
- src/modules/rabbitmq/handlers/price.discovery.handler.service.ts
- src/modules/rabbitmq/rabbitmq.consumer.ts
- src/services/analytics/interfaces/analytics.query.interface.ts
- src/services/analytics/mocks/analytics.query.service.mock.ts
- src/services/analytics/services/analytics.query.service.ts
- src/services/analytics/timescaledb/entities/timescaledb.entities.ts
- src/services/analytics/timescaledb/migration/1684167998347-xExchange.ts
- src/services/analytics/timescaledb/migration/typeOrm.config.ts
- src/services/analytics/timescaledb/timescaledb.module.ts
- src/services/analytics/timescaledb/timescaledb.query.service.ts
- src/services/crons/price.discovery.cache.warmer.service.ts
- transition from AWS timestream to timescaleDB only
- use optimised queries for price discovery charts
- added new continuous aggregate for price discovery chart values
- use last registered values for price discovery launched and accepted tokens
- code cleanup
- last tokens price: `acceptedTokenPriceUSD` and `launchedTokenPriceUSD` should remain the same even after price change on swaps
```
query PriceDiscovery {
priceDiscoveryContracts {
address
acceptedTokenPrice
acceptedTokenPriceUSD
launchedTokenPrice
launchedTokenPriceUSD
}
}
```
- closing values:
```
query ClosedValues {
closingValues(
priceDiscoveryAddress: "erd1qqqqqqqqqqqqqpgq6dszt34rl3zffwvfce8meq8e63zss5v70n4srreusz",
metric: "launchedTokenPrice",
bucket: MINUTES_30
) {
timestamp
value
}
}
```
> [SERVICES-1573] price discovery new charts

- src/modules/pair/services/pair.abi.service.ts
- src/modules/pair/services/pair.setter.service.ts
- src/modules/rabbitmq/handlers/pair.handler.service.ts
- src/modules/rabbitmq/handlers/pair.swap.handler.service.ts
- src/services/crons/pair.cache.warmer.service.ts
- real time updates on pair info with fall back to cron job
- added correct cache for token reserves
- added token price usd and pair info refresh in cachewarmer
- added token price usd and pair info refresh in rabbitmq events
- with `ENABLE_CACHE_WARMER=true` pair reserves should be updated every 12 seconds(cron job interval);
- with `ENABLE_EVENTS_NOTIFIER=true` pair reserves should be updated after each event generated by pair(liquidity event or swap)
> [SERVICES-1657] improve pair reserves caching update

- src/modules/rabbitmq/handlers/pair.swap.handler.service.ts
- src/services/crons/pair.cache.warmer.service.ts
- token price USD from pair cache doesn't update correctly
- remove update from pair cache warmer
- N/A
> [SERVICES-1657] remove update of tokenPriceUSD from pair

- src/abis/router.abi.json
- src/config/default.json
- src/helpers/decorators/error.logger.ts
- src/modules/router/mocks/router.abi.service.mock.ts
- src/modules/router/models/factory.model.ts
- src/modules/router/router.resolver.ts
- src/modules/router/services/interfaces.ts
- src/modules/router/services/router.abi.service.ts
- src/modules/router/services/router.transactions.service.ts
- src/modules/router/specs/router.transactions.service.spec.ts
- update router smart contract to accept multiple tokens for automatic pair swap enable
- updated swap enable config to return an array of configs for each accepted token
- fixed user swap enable transaction input validation
```
query Router {
factory {
address
pairCreationEnabled
commonTokensForUserPairs
enableSwapByUserConfig {
lockingSC {
address
lockedToken {
collection
}
lpProxyToken {collection}
farmProxyToken {collection}
}
commonTokenID
minLockedTokenValue
minLockPeriodEpochs
}
}
}
```
- query should return an array of configs for `enableSwapByUserConfig` field
> [SERVICES-1670] router swap enable map

- src/config/default.json
- src/modules/token-unstake/services/token.unstake.transaction.service.ts
- src/modules/token-unstake/specs/token.unstake.transaction.service.spec.ts
- src/modules/token-unstake/token.unstake.resolver.ts
- gasLimit for cancelUnbond was static, no matter how many unlocked tokens a user has. This approach has the disadvantage of giving too much gas for few tokens and too little for many tokens
- compute the gasLimit in a dynamic way depending on the number of unlocked tokens for user
- cancelUnbond transaction shall have 9.5mil gasLimit for 1 unlocked tokens
- cancelUnbond transaction shall have 10.5mil gasLimit for 2 unlocked tokens
- cancelUnbond transaction shall have 21.5mil gasLimit for 13 unlocked tokens
> SERVICES-1687: dynamic gasLimit for cancelUnbond

- src/config/default.json
- match xExchange's minimum swap amount
- update default config of minimum swap
```
query {
factory {
minSwapAmount
}
}
```
- query should return new value
> [SERVICES-1690] update min swap

- src/modules/tokens/services/token.compute.service.ts
- token price is computed using the pair with most liquidity; if there is an `ActiveNoSwap` and an `Active` pair, only the `Active` should be used
- use only Active pairs for token price computation if there are at least 1 active pair
- use all pairs for token price computation if there are no active pairs
```
query Tokens {
tokens(identifiers: ["KOSON-5dd4fa", "TRO-94c925"]) {
identifier
decimals
price
}
}
```
- on mainnet, `KOSON-5dd4fa` should express token price from USDC pair
> [SERVICES-1695]: fix token compute price EGLD

- src/utils/token.type.compare.ts
- keep backwards compatibility for pair types
- for any `Jungle` based type return `Experimental` or upper type
```
query {
pairs(offset:0, limit: 100) {
address
type
}
}
```
- query should return type for all pairs; for `Jungle` tokens return `Experimental`; for `Jungle-*` return upper type
> [SERVICES-1670] backwards compatibility for pair type

- src/modules/rabbitmq/handlers/router.handler.service.ts
- token type create check for hardcoded common token
- use router's common tokens to check for create token type when new pair is created
- on new pair created for new token paired with a common token, type should be created for the token
> [SERVICES-1670] fix token type create

- src/modules/price-discovery/services/price.discovery.compute.service.ts
- src/modules/rabbitmq/handlers/price.discovery.handler.service.ts
- src/services/analytics/interfaces/analytics.query.interface.ts
- src/services/analytics/services/analytics.query.service.ts
- src/services/analytics/timescaledb/entities/timescaledb.entities.ts
- src/services/analytics/timescaledb/migration/1684167998347-xExchange.ts
- src/services/analytics/timescaledb/timescaledb.query.service.ts
- src/services/multiversx-communication/mx.api.service.ts
- price discovery charts data display only the last 1 day of data
- remove time constraint from materialized view
- add time interval to get price discovery chart data
```
query {
closingValues(
priceDiscoveryAddress: "erd1qqqqqqqqqqqqqpgq6dszt34rl3zffwvfce8meq8e63zss5v70n4srreusz",
metric: "launchedTokenPrice",
bucket: MINUTE_1
) {
timestamp
value
}
}
```
- query should return values between price discovery phase
> [SERVICES-1573] fix price discovery charts

- src/modules/rabbitmq/handlers/router.handler.service.ts
- src/modules/rabbitmq/rabbitmq.consumer.ts
- pair filtering uses the cached values
- use raw methods to get all pairs on create pair event and update filtering for events
- N/A
> [SERVICES-1704] fix new pair filtering for events

- src/modules/governance/governance.contract.resolver.ts
- src/modules/governance/governance.energy.contract.resolver.ts
- src/modules/governance/governance.module.ts
- src/modules/governance/governance.query.resolver.ts
- src/modules/governance/models/contracts.filter.args.ts
- src/modules/governance/models/energy.contract.model.ts
- src/modules/governance/models/governance.union.ts
- src/modules/governance/services/governance.service.ts
- src/utils/governance.ts
- Implement fragments and filters for governance module
> MEX-322: fragments & filters

- src/config/default.json
- issue lp token insufficient gas
- increase gas limit for issue lp token and set local roles
- N/A
> Gas limit for issue lp token and set local roles

- src/modules/fees-collector/fees-collector.resolver.ts
- src/modules/fees-collector/models/fees-collector.model.ts
- src/modules/fees-collector/services/fees-collector.abi.service.ts
- fees collector didn't exposed all information
- add missing `allTokens` field resolver
- expose fees collector known contracts on fees collector model
```
query FeesCollector {
feesCollector {
allTokens
knownContracts
}
}
```
- query should return valid values
> [MEX-332] fees collector known contracts

- src/config/default.json
- src/modules/fees-collector/fees-collector.resolver.ts
- src/modules/fees-collector/services/fees-collector.transaction.service.ts
- src/modules/fees-collector/specs/fees-collector.transaction.service.spec.ts
- fees collector resolver missed some of admin endpoints
- add known contracts update endpoints
- add known tokens update endpoints
> [MEX-331] fees collector admin endpoints

- src/config/default.json
- src/config/test.json
- src/modules/pair/mocks/pair.constants.ts
- src/modules/staking/models/staking.model.ts
- src/modules/staking/services/staking.compute.service.ts
- src/modules/staking/specs/staking.compute.service.spec.ts
- src/modules/staking/staking.resolver.ts
- src/modules/tokens/mocks/token.getter.service.mock.ts
- staking contracts positions can be compounded directly without rewards harvesting; because investment and rewards are the same type, we can compound the rewards and calculate the optimal frequency for compounding
- add method to compute optimal compound frequency for any staking position expressed in hours and minutes interval
```
query OptimalCompound {
getOptimalCompoundFrequency(
stakeAddress: "erd1qqqqqqqqqqqqqpgq8w0s682m88xae2ne3qkq7w2h26u5a5c00n4stt02d7",
amount: "900000000000000000000",
timeInterval: 365
) {
interval
hours
minutes
}
}
```
- query should return an OptimalCompound object
```
{
"optimalProfit": 114.31687566993836,
"interval": 34,
"days": 10,
"hours": 17,
"minutes": 38
}
```
> [SERVICES-1740] optimal staking compound

- src/config/mainnet.json
> MEX-349: add UTK governance SC address

- src/modules/governance/models/governance.contract.model.ts
- src/modules/governance/resolvers/governance.contract.resolver.ts
- src/modules/governance/services/governance.abi.service.ts
- frontend needs the SC shard in order to compute timers based on block numbers
> MEX-351: governance contract shard field

- src/modules/governance/resolvers/governance.proposal.resolver.ts
- userVotingPower depends on the rootHash field that is not yet resolved
> MEX-352: fix userVotingPower

- src/modules/user/services/userEnergy/user.energy.compute.service.ts
- src/modules/user/specs/user.energy.compute.service.spec.ts
- Outdated claim progress flag is not taken into account when an outdated contract is verified
- check also the outdated claim progress when compute outdated contracts
```
query UserOutdatedContracts {
userOutdatedContracts {
address
type
claimProgressOutdated
}
}
```
- query should return a contract event when the energy is in sync but boosted rewards was not harvested
> [MEX-353] fix outdated claim progress

- src/modules/staking/services/staking.compute.service.ts
- src/modules/staking/specs/staking.compute.service.spec.ts
- rewards generated from small positions can not cover the transactions fees
- return zero values for small positions of staked tokens
```
query OptimalCompound {
getOptimalCompoundFrequency(
stakeAddress: "erd1qqqqqqqqqqqqqpgqzps75vsk97w9nsx2cenv2r2tyxl4fl402jpsx78m9j",
amount: "5063512981963332000",
timeInterval: 365
) {
optimalProfit
interval
days
hours
minutes
}
}
```
- query should return `0` on mainnet
> [SERVICES-1740] optimal staking compound fix

- src/modules/user/services/userEnergy/user.energy.compute.service.ts
- src/modules/user/specs/user.energy.compute.service.spec.ts
- users with no claim progress in farms or fees collector should not get outdated energy pop-up for these contracts
- add check for claim progress week
```
query UserOutdatedContracts {
userOutdatedContracts {
address
type
claimProgressOutdated
}
}
```
- query should return empty array for accounts with no energy
> [MEX-353] fix outdated contracts for users with no energy

- src/abis/farms/v2/farm-with-locked-rewards.abi.json
- src/modules/farm/v2/services/farm.v2.abi.service.ts
- `getBoostedYieldsRewardsPercentage` typo fix in abi
- update farm v2 ABI and endpint call
```
query Farms {
farms {
... on FarmModelV2 {
boostedYieldsRewardsPercenatage
}
}
}
```
- query should return values
> SERVICES-1791: fix farm v2 endpoint from latest release

- src/config/devnet.json
- current devnet farms are not upgradable
- update devnet farm addresses with new ones
```
query Farms {
farms {
... on FarmModelV2 {
address
burnGasLimit
boostedYieldsFactors {
maxRewardsFactor
minFarmAmount
minEnergyAmount
userRewardsFarm
userRewardsEnergy
}
boostedYieldsRewardsPercenatage
divisionSafetyConstant
energyFactoryAddress
farmedToken {identifier}
farmedTokenPriceUSD
farmingToken {identifier}
farmingTokenPriceUSD
farmToken {collection}
farmTokenPriceUSD
farmTokenSupply
lastErrorMessage
lastRewardBlockNonce
minimumFarmingEpochs
pair {address}
penaltyPercent
perBlockRewards
produceRewardsEnabled
rewardPerShare
rewardReserve
state
totalValueLockedUSD
transferExecGasLimit
version
lastGlobalUpdateWeek
optimalEnergyPerLp
rewardType
time {
scAddress
firstWeekStartEpoch …
```
> [SERVICES-1801] new devnet farm addresses

- src/modules/pair/services/pair.compute.service.ts
- src/modules/pair/specs/pair.compute.service.spec.ts
- fix compute lp token price in USD
- use correct denominations for tokens involved in lp token price compute USD
```
query Pairs {
pairs(offset: 0, limit: 100) {
address
liquidityPoolTokenPriceUSD
}
}
``` 
- query should return correct values for lp token price in USD
> [SERVICES-1813] fix lp token price usd

- src/config/mainnet.json
- src/config/staging.json
- specialized configs are overwritten from default if not available
- add empty governance addresses for mainnet / staging
```
query Governance {
governanceContracts {
... on GovernanceTokenSnapshotContract {
address
feeToken {
identifier
}
}
}
}
```
> [MEX-363] fix governance addresses

- src/modules/escrow/services/escrow.abi.service.ts
- src/modules/escrow/services/escrow.setter.service.ts
- src/modules/escrow/specs/escrow.abi.service.spec.ts
- src/modules/rabbitmq/handlers/escrow.handler.service.ts
- escrow queries ends calling SC via vm-queries or get all keys for every user
- cache escrow SC keys to be used for all users
- cache all addresses that has at least one permission in escrow SC
- use cached escrow SC keys to get all receivers for a sender
```
escrowPermissions
escrowReceivers
```
- queries should resolve in lesser time
> [SERVICES-1824] improve escrow queries

- src/config/default.json
- failed multi pair swap transactions with not enough gas
- increase gas limit multiplier for multi pair txs
- N/A
> Increase gas limit for multi pair txs

- src/helpers/elastic.service.ts
- memory leak on ES service leads to OOM restarts
- create json query before sending to elastic client
- N/A
> [SERVICES-1831] fix memory leak in elastic service

- src/services/analytics/timescaledb/timescaledb.module.ts
- src/services/crons/logs.processor.service.ts
- wrong check for cached value
- check for `undefined` for values cached
- N/A
> [SERVICES-1832] fix logs processor lastProcessedTimestamp

- src/modules/auto-router/auto-router.resolver.ts
- src/modules/auto-router/models/auto-route.model.ts
- 3rd party APIs could not get transctions for users without auth token
- add a special unauthenticated field to get transactions for a user
```
query Swap {
swap(
tokenInID: "EGLD",
amountIn: "1000000000",
tokenOutID: "USDC-8d4068",
) {
swapType
tokenInID
tokenOutID
tokenInExchangeRate
tokenOutExchangeRate
tokenInPriceUSD
tokenOutPriceUSD
tokenRoute
intermediaryAmounts
amountOut
fees
pricesImpact
noAuthtransactions(sender: "")
}
}
```
- query should return transactions event without auth token
> [SERVICES-1863] add new no auth transaction field for auto router

- src/modules/farm/base-module/services/farm.abi.service.ts
- src/modules/farm/base-module/services/farm.compute.service.ts
- src/modules/farm/base-module/services/interfaces.ts
- src/modules/farm/mocks/farm.abi.service.mock.ts
- src/modules/farm/mocks/farm.compute.service.mock.ts
- src/modules/farm/v2/services/farm.v2.abi.service.ts
- src/modules/farm/v2/services/farm.v2.compute.service.ts
- computed minted rewards used for compute rewards for position used full rewards instead of only base rewards
- extract compute minted rewards in a method; for farm v2 override base implementation to return only base rewards
- use farm shard ID fetched from network
- `getRewardsForPosition` query should return the same values for both `vmQuery: true` and `vmQuery: false` for a position(might have a slight deviation based on timing to execute and caches)
> [SERVICES-1871] fix farm v2 base rewards

- package-lock.json
- package.json
- src/modules/rabbitmq/handlers/farm.handler.service.ts
- src/modules/rabbitmq/rabbitmq.consumer.ts
- src/modules/rabbitmq/rabbitmq.farm.handler.service.ts
- src/modules/rabbitmq/rabbitmq.module.ts
- missing handlers for farm v2 events
- added new methods to handle farm v2 events
- update rabbitmq handler to handle farm v2 events using new handlers
- with `ENABLE_EVENTS_NOTIFIER=true` farm v2 events should be handled
> [SERVICES-1877] farm v2 events

- src/config/test.json
- src/modules/analytics/specs/analytics.service.spec.ts
- src/modules/farm/mocks/farm.constants.ts
- src/modules/farm/mocks/farm.v2.abi.service.mock.ts
- src/modules/farm/specs/farm.service.spec.ts
- src/modules/farm/specs/farm.v2.transactions.service.spec.ts
- src/modules/farm/v2/farm.v2.module.ts
- src/modules/farm/v2/farm.v2.transaction.resolver.ts
- src/modules/farm/v2/services/farm.v2.abi.service.ts
- src/modules/farm/v2/services/farm.v2.transaction.service.ts
- src/modules/farm/v2/services/interfaces.ts
- src/modules/proxy/mocks/proxy.abi.service.mock.ts
- src/modules/proxy/proxy.transaction.resolver.ts
- src/modules/proxy/services/proxy-farm/proxy.farm.module.ts
- src/modules/proxy/services/proxy-farm/proxy.farm.transactions.service.ts
- src/modules/proxy/specs/proxy-pair-transactions.service.spec.ts
- src/modules/proxy/specs/proxy.farm.transactions.service.spec.ts
- src/modules/proxy/validators/proxy.address.validator.ts
- src/services/multiversx-communication/mx.api.service.mock.ts
- users will have to initialize the total farm position with all their positions on a farm;
- users will perform a migration by claiming rewards with all the positions;
- added method to get farm token migration nonce from smart contract;
- added method to generate claim rewards transactions for all farm positions with lower nonce than migration nonce;
```
query MigrateToFarmPosition {
migrateTotalFarmPositionsProxy(
proxyAddress: <proxy_address>
) {
data
}
}
```
```
query MigrateToFarmPosition {
migrateTotalFarmPositions(
farmAddress: <farm_address>
) {
data
}
}
```
- queries should return transactions if user had positions in farm prior to upgrade
> [MEX-376] migrate positions transactions

- src/modules/staking/models/staking.model.ts
- src/modules/staking/services/staking.abi.service.ts
- src/modules/staking/services/staking.compute.service.ts
- src/modules/staking/staking.module.ts
- src/modules/staking/staking.resolver.ts
- src/submodules/weekly-rewards-splitting/services/weekly-rewards-splitting.abi.service.ts
- src/submodules/weekly-rewards-splitting/weekly-rewards-splitting.module.ts
- integrate weekly rewards splitting submodule into farm staking model
- added new fields into staking model
- added field resolvers for new fields
- added methods to get information for new field resolvers
```
query Staking {
stakingFarms {
address
energyFactoryAddress
lastGlobalUpdateWeek
undistributedBoostedRewards
undistributedBoostedRewardsClaimed
boosterRewards {
scAddress
apr
week
totalEnergyForWeek
totalLockedTokensForWeek
totalRewardsForWeek {
tokenID
nonce
amount
}
rewardsDistributionForWeek {
tokenId
percentage
}
}
}
}
```
> [MEX-405] weekly rewards splitting integration

- package-lock.json
- package.json
- src/config/default.json
- src/modules/rabbitmq/handlers/staking.handler.service.ts
- src/modules/rabbitmq/rabbitmq.consumer.ts
- src/modules/rabbitmq/rabbitmq.module.ts
- src/modules/staking/models/staking.model.ts
- src/modules/staking/services/staking.abi.service.ts
- src/modules/staking/services/staking.compute.service.ts
- src/modules/staking/services/staking.service.ts
- src/modules/staking/specs/staking.compute.service.spec.ts
- src/modules/staking/specs/staking.service.spec.ts
- src/modules/staking/staking.resolver.ts
- src/modules/user/models/user.model.ts
- src/modules/user/services/userEnergy/user.energy.compute.service.ts
- src/modules/user/user.info-by-week.resolver.ts
- add support for boosted rewards into staking module
- added new fields into staking model for boosted rewards information
- added compute method for user's boosted rewards from staking contract
- added outdated energy compute for staking contract
```
query StakingRewards {
getStakingRewardsForPosition(
computeBoosted: true,
stakingPositions: {
farmsPositions: [
{
farmAddress: <staking_address>,
user: <user_address>,
liquidity: ,
attributes: ,
identifier: 
}
]
}
) {
rewards
claimProgress {
week
energy {
amount
lastUpdateEpoch
totalLockedTokens
}
}
boostedRewardsWeeklyInfo {
scAddress
userAddress
week
positionAmount
apr
energyForWeek {
amount
lastUpdateEpoch
totalLockedTokens
}
rewardsDistributionForWeek {
tokenId
percentage
}
rewardsForWeek {
tokenID
amount
}
}
}
}
``` …
> [MEX-407] compute boosted rewards

- src/modules/auto-router/auto-router.resolver.ts
- src/modules/auto-router/services/auto-router.compute.service.ts
- src/modules/auto-router/services/auto-router.service.ts
- swap query didn't return user friendly errors
- added error handling for swap query
```
query Swap {
swap(
tokenInID: <tokenID>,
tokenOutID: <tokenID>,
tolerance: 0.01,
amountOut: <amount>
) {
swapType
amountIn
amountOut
fees
pricesImpact
tokenInExchangeRate
tokenOutExchangeRate
}
}
```
- query should return error if no route found for multi swap
- query should return error on swap output type if amount is grater than reserves
> [SERVICES-1909] fix swap errors

- src/modules/staking/mocks/staking.abi.service.mock.ts
- src/modules/staking/models/staking.model.ts
- src/modules/staking/services/interfaces.ts
- src/modules/staking/services/staking.abi.service.ts
- src/modules/staking/services/staking.transactions.service.ts
- src/modules/staking/specs/staking.transactions.service.spec.ts
- src/modules/staking/staking.resolver.ts
- users have to perform at least one action with the existing staking tokens to start earn boosted rewards
- added query to return a migration transaction for current staking positions; proposed transaction is a claim rewards
```
query TotalStakingMigrate {
migrateTotalStakingPosition(
stakeAddress: <staking_address>
) {
data
}
}
```
- query should return transactions if user has at least one current staking position
> [MEX-409] staking migration to boosted rewards

- src/modules/position-creator/position.creator.transaction.resolver.ts
- src/modules/position-creator/services/position.creator.transaction.ts
- src/modules/position-creator/specs/position.creator.transaction.spec.ts
- transactions with EGLD and consolidate tokens have to be batched for EGLD wrap
- added EGLD wrap for transactions with consolidate tokens sent
```
query CreateFarmPositionSingleToken {
createFarmPositionSingleToken(
farmAddress: "erd1qqqqqqqqqqqqqpgq3chrzjdg3gu40zt6kes6w62cyz8tes6k0n4ssk3hj4",
payments: [{
tokenID: "EGLD",
nonce: 0,
amount: "1000000000000000000"
},
{
tokenID: <farm_token_id>,
nonce: 0,
}
],
) {
receiver
data
}
}
```
- query should return 2 transactions: wrap + create farm position from single token
> [MEX-410] position creator batch transaction

- src/modules/farm/models/farm.model.ts
- src/modules/farm/v2/farm.v2.resolver.ts
- src/modules/farm/v2/farm.v2.transaction.resolver.ts
- src/modules/farm/v2/services/farm.v2.service.ts
- src/modules/farm/v2/services/farm.v2.transaction.service.ts
- src/modules/position-creator/position.creator.module.ts
- boosted rewards from farms are now split from the base rewards
- add query to get only the farm boosted rewards for a user
- add query to generate transaction to claim only boosted rewards
```
query FarmBoostedRewards {
getFarmBoostedRewardsBatch(
farmsAddresses: [<farm_address_1>, <farm_address_2>]
) {
farmAddress
claimProgress {
energy {
amount
}
week
}
boostedRewardsWeeklyInfo {
scAddress
userAddress
rewardsForWeek {
tokenID
amount
}
}
}
}
```
- query should return an array with all boosted rewards from farms for a user
```
query ClaimBoostedRewards {
claimFarmBoostedRewards(
farmAddress: <farm_address>
) {
sender
receiver
data
gasLimit
}
}
```
- query should return transaction to claim boosted rewards
> [MEX-416] farm boosted rewards

- src/config/default.json
- src/modules/staking/services/staking.service.ts
- src/modules/staking/staking.resolver.ts
- boosted rewards for staking can now be split between base rewards and boosted rewards
- add query to get only boosted rewards for an user from multiple staking contracts
```
query StakingBoostedRewardsBatch {
stakingAddresses: [""]
) {
farmAddress
}
}
```
> [MEX-416] get boosted rewards

- src/modules/escrow/services/escrow.transaction.service.ts
- src/modules/escrow/specs/escrow.transaction.service.spec.ts
- sender should not be able to send fund to himself
- throw error if sender and receiver address for `lockFunds` are the same
```
query TransferFunds {
escrowTransfer(
receiver: <sender_address>,
inputTokens: [
{
tokenID: <token_id>,
nonce: 1,
},
]
) {
receiver
gasLimit
data
}
}
```
- query should return error
> [SERVICES-2035] escrow check sender & receiver

- src/abis/locked-token-pos-creator.abi.json
- src/config/default.json
- src/modules/position-creator/position.creator.module.ts
- src/modules/position-creator/position.creator.transaction.resolver.ts
- src/modules/position-creator/services/position.creator.compute.ts
- src/modules/position-creator/services/position.creator.transaction.ts
- src/modules/position-creator/specs/position.creator.transaction.spec.ts
- src/services/multiversx-communication/mx.proxy.service.ts
- create xMEX positions with any token
- create xMEX liquidity position with any token
- create xMEX farm position with any token
- add query to generate transaction for create xMEX position from any token
- update create liquidity and farm position to accept lockEpochs and generate transaction for energy position creator
- update farm position with two tokens to accept xMEX tokens and generate transaction for energy position creator
- create energy position
```
query CreateEnergyPosition {
createEnergyPosition(
payment: {
tokenID: <token_id>,
nonce: 0,
},
lockEpochs: 1440,
) {
data
}
}
```
- create locked position single token
```
query CreatePositionSingleToken {
createPositionSingleToken(
pairAddress: <pair_address>,
payment: {
tokenID: <token_id>, …
```
> [MEX-417] energy position creator

- src/modules/staking/services/staking.service.ts
- missing field for returned BoostedRewardsModel
- added `farmAddress` field
```
query StakingBoostedRewardsBatch {
stakingAddresses: [<address>]
) {
farmAddress
}
}
```
- query should return an address for `farmAddress` field
> [MEX-416] Missing field for staking BoostedRewardsModel

- src/abis/farm-staking.abi.json
- src/config/default.json
- src/modules/staking/services/staking.transactions.service.ts
- src/modules/staking/specs/staking.transactions.service.spec.ts
- src/modules/staking/staking.resolver.ts
- users can claim only boosted rewards from staking contracts
- added transaction generation for claiming boosted rewards from staking contracts
```
query ClaimStakingBoostedRewards {
claimStakingBoostedRewards(stakeAddress: <stake_address>) {
receiver
data
}
}
```
- query should return transaction
> [MEX-418] claim boosted rewards

- src/modules/tokens/token.resolver.ts
- previous price might not exist if tokens have no swaps
- return null for token previous price if no price is available
```
query Tokens {
tokens {
identifier
previous24hPrice
}
}
```
- query should return `null` for `previous24hPrice` for tokens with no previous price
> [SERVICES-2040] return null if no previous price

- src/modules/farm/models/farm.model.ts
- src/modules/farm/v2/farm.v2.resolver.ts
- src/modules/staking/staking.resolver.ts
- src/modules/staking/validators/stake.address.validator.ts
- easier way for clients to get a list of all boosted positions amounts from all farms or staking
- added a new model to return sc address and user boosted position
- updated queries to return an array of user boosted position from an array of sc addresses as input
- 
```
query UserTotalFarmPosition {
userTotalFarmPosition(farmsAddresses:
[<farm_address>]
){
address
boostedTokensAmount
}
}
```
- query should return an array of boosted positions amounts
> [MEX-372] user total boosted position

- src/modules/position-creator/services/position.creator.transaction.ts
- src/modules/position-creator/specs/position.creator.transaction.spec.ts
- position creator transactions with EGLD and single token have different behaviour between consolidation of a position or create a new one
- add wrap EGLD only for position creator transactions with position consolidate
- use value for position transactions with EGLD and no consolidation
```
query CreateStakingPositionSingleToken {
createStakingPositionSingleToken(
stakingAddress: <staking_address>,
payments: [{
amount: "1000000000000000000",
nonce: 0,
tokenID: "EGLD"
}],
) {
receiver
value
data
}
}
```
- query should return one transaction with value
```
query CreateStakingPositionSingleToken {
createStakingPositionSingleToken(
stakingAddress: <stake_address>,
payments: [{
amount: "1000000000000000000",
nonce: 0,
tokenID: "EGLD"
},
{
amount: "1000000000000000000",
nonce: …
```
> [MEX-410] position creator with EGLD

- src/modules/position-creator/services/position.creator.compute.ts
- src/modules/position-creator/services/position.creator.transaction.ts
- src/modules/position-creator/specs/position.creator.transaction.spec.ts
- position creator SC accepts lp token to convert it into a dual yield position
- update createDualFarmPositionSingleToken to create transaction from lp token
```
query CreateDualFarmPositionSingleToken {
createDualFarmPositionSingleToken(
dualFarmAddress: <dual_farm_address>,
payments: [{
tokenID: <lp_token_id>,
nonce: 0,
}],
) {
receiver
data
}
}
```
- query should return transaction if valid lp token is used
> [MEX-410] dual yield position from lp token

- src/modules/proxy/proxy.transaction.resolver.ts
- src/modules/proxy/services/proxy-farm/proxy.farm.transactions.service.ts
- proxy dex can increase the energy for a xmex from a wrapped farm token
- added query to generate transaction that increases the energy of xmex from XMEXFARM token
```
query IncreaseProxyFarmTokenEnergy {
increaseProxyFarmTokenEnergy(
payment: {
tokenID: <proxy_farm_token_id>,
nonce: <nonce>,
},
lockEpochs: 360
) {
data
}
}
```
- query should return transaction
> [MEX-397] xmex farm position energy increase

- src/modules/auth/gql.auth.guard.ts
- src/modules/auth/jwt.or.native.auth.guard.ts
- src/modules/auto-router/specs/auto-router.service.spec.ts
- src/modules/fees-collector/specs/fees.collector.compute.service.spec.ts
- src/modules/pair/specs/pair.compute.service.spec.ts
- src/modules/pair/specs/pair.service.spec.ts
- src/modules/pair/specs/pair.transactions.service.spec.ts
- src/modules/proxy/specs/proxy-pair-transactions.service.spec.ts
- src/modules/router/specs/router.transactions.service.spec.ts
- src/modules/staking/specs/staking.transactions.service.spec.ts
- src/modules/tokens/specs/token.compute.service.spec.ts
- src/modules/user/services/user.metaEsdt.service.ts
- src/modules/user/services/userEnergy/user.energy.compute.service.ts
- src/services/context/context.getter.service.ts
- src/services/context/mocks/context.getter.service.mock.ts
- src/services/crons/cache.warmer.service.ts
- src/services/crons/metabonding.cache.warmer.service.ts
- src/services/crons/pair.cache.warmer.service.ts
- src/services/multiversx-communication/mx.api.service.ts
- src/submodules/weekly-rewards-splitting/specs/weekly-rewards-splitting.compute.service.spec.ts
- src/utils/metrics.collector.ts
- request user nfts from multiple places in the same block would not change the actual return from API
- add a block time caching for user nfts; multiple requests to the same resource should be retrieved from cache
- N/A
> [SERVICES-2105] improve user nfts request

- src/services/context/context.getter.service.ts
> [SERVICES-2105] revert user nfts caching

- src/modules/staking/models/staking.model.ts
- src/modules/staking/services/staking.compute.service.ts
- src/modules/staking/specs/staking.compute.service.spec.ts
- src/modules/staking/staking.resolver.ts
- compute the remaining days to distribute all rewards
- added a new field for staking model: `rewardsRemainingDays`
- added method to compute remaining days to distribute all rewards
```
query Staking {
stakingFarms {
address
rewardsRemainingDays
}
}
```
- query should return the remaining days to distribute all rewards
> [SERVICES-2130] staking rewards remaining days

- src/modules/rabbitmq/handlers/weeklyRewardsSplitting.handler.service.ts
- src/modules/staking/services/staking.setter.service.ts
- staking contracts with boosted rewards now creates the same `claim_multi_event`
- add check in `getSetter` from `WeeklyRewardsSplittingHandlerService` for staking contract and return specific setter service
- N/A
> [MEX-418] fix handler for claim multi rewards event on staking contracts

- src/config/default.json
- src/modules/farm/models/farm.args.ts
- src/modules/farm/v2/services/farm.v2.transaction.service.ts
- new farm v2 doesn't require the exit amount argument for `exitFarm` endpoint
- removed exit amount argument from `exitFarm` transaction generation
- N/A
> [MEX-437] no exit amount

- src/config/default.json
- insufficient gas
- update gas limit for unstake staking position
- N/A
> MEX-418: update gas limit for unstake staking position

- src/config/default.json
- src/modules/staking-proxy/services/staking.proxy.transactions.service.ts
- staking proxy no longer require exit amount on unstake farm tokens transction
- removed exit amount from staking proxy unstake farm tokens
- N/A
> [MEX-437] remove exit amount from staking proxy unstake farm tokens

- src/modules/position-creator/position.creator.transaction.resolver.ts
- src/modules/position-creator/services/position.creator.transaction.ts
- src/modules/position-creator/specs/position.creator.transaction.spec.ts
- accept EGLD as payment for creating dual farm position with dual tokens
- added wrap transaction in case EGLD is used as payment for creating dual farm position from 2 tokens
```
query CreateDualFarmPositionDualTokens {
createDualFarmPositionDualTokens(
dualFarmAddress: <staking_proxy_address>,
tolerance: 0.01,
payments: [
{
tokenID: "EGLD",
nonce: 0,
},
{
tokenID: <token_id>,
nonce: 0,
}
]
) {
receiver
data
}
}
```
- query should return 2 transactions
> [MEX-410] position creator dual farm EGLD token

- src/config/default.json
- src/modules/position-creator/services/position.creator.transaction.ts
- src/modules/position-creator/specs/position.creator.transaction.spec.ts
- use specific gas limit for position creator on farm position with dual tokens and locked tokens
- added new gas config for farmPositionProxy
- N/A
> [MEX-443]: use specific gas limit

- src/helpers/api.config.service.ts
- src/helpers/decorators/caching.decorator.ts
- src/helpers/proxy.network.provider.profiler.ts
- src/services/multiversx-communication/mx.api.service.ts
- src/services/multiversx-communication/mx.proxy.service.ts
- src/utils/logging.interceptor.ts
- use timestamp to query data from deep history
- added context tracker from nestjs-sdk
- use context tracker to propagate timestamp across services
- query data with timestamp
- any query with `timestamp` in request headers should return data from the past
> [SERVICES-2155] context tracker

- src/modules/farm/v2/farm.v2.transaction.resolver.ts
- src/modules/staking/staking.resolver.ts
- easier handling from client side implementation to pass an array of addresses
- update migrate total farm position endpoints to accept an array of sc addresses to return the migration transactions
- N/A
> [MEX-376] accept array of addresses for migrate transactions

- src/modules/analytics/services/analytics.aws.setter.service.ts
- cache expires before end of cron job
- increase cache time for analytics
- N/A
> [SERVICES-2204] increase cache time for analytics

- src/services/analytics/timescaledb/timescaledb.module.ts
- src/services/analytics/timescaledb/timescaledb.query.service.ts
- too many queries to get the first timestamp for same series
- cache the first available timestamp for a series to be used for time bucket queries on daily aggregates
- N/A
> [SERVICES-2204] cache first timestamp for analytics series

- src/config/default.json
- not enough gas for enable swaps transaction
- increase gas limit for enable swaps
- N/A
> [config] increase gas limit for swap enable

- src/modules/analytics/services/analytics.aws.getter.service.ts
- unavailable data for series will throw error for all the requests in the same query
- return empty array if no data is available for cached data
- N/A
> [SERVICES-2204] return empty values for analytics if no data is found

- src/config/default.json
- not enough gas for router transactions
- update config gas limits for router
- N/A
> [config] update gas limits for router operations

- src/abis/composable-tasks.abi.json
- src/modules/auto-router/services/auto-router.service.ts
- src/modules/auto-router/specs/auto-router.service.spec.ts
- src/modules/composable-tasks/services/composable.tasks.transaction.ts
- src/modules/composable-tasks/specs/composable.tasks.transaction.spec.ts
- src/modules/pair/pair.resolver.ts
- src/modules/pair/services/pair.transactions.service.ts
- src/modules/pair/specs/pair.transactions.service.spec.ts
- swap composable task can now choose which swap endpoint can use
- updated the compose swap transaction method to accept the swap endpoint used to perform the swap
- updated the pair swap with fixed output transaction generator to use composable tasks for EGLD
```
query SwapTokensFixedOutput {
swapTokensFixedOutput(
pairAddress: <address>
tokenInID: "EGLD"
tokenOutID: <token_identifier>
amountIn: <amount_in>
amountOut: <amount_out>
) {
data
}
}
```
- query should return a`composeTasks` transaction with fixed output swap
> [MEX-414] composable tasks with specific swap endpoint

- src/modules/pair/mocks/pair.compute.service.mock.ts
- src/modules/pair/services/pair.compute.service.ts
- src/modules/pair/services/pair.transactions.service.ts
- src/modules/pair/specs/pair.compute.service.spec.ts
- src/modules/pair/specs/pair.transactions.service.spec.ts
- permanently liquidity locked remaining in a pair should not be grater than 1 USD
- added method to compute permanently liquidity locked in pair when initial adding liquidity
- added check in addInitialLiquidity method for minimum amounts
- added check in addInitialLiquidity method for maximum permanently liquidity locked
```
query AddInitialLiquidity {
addInitialLiquidityBatch(
pairAddress: <pair_address>
tokens: [
{ tokenID: <token_identifier>, nonce: 0, amount: <amount>}
{ tokenID: <token_identifier>, nonce: 0, amount: <amount> }
]
tolerance: 0.1
) {
data
}
}
```
- query should return error if any of the 2 amounts are less than 1000 units
- query should return error if the liquidity locked permanently is grater than 1 USD
> [SERVICES-2290] check for maximum liquidity locked permanently in pair

- src/modules/position-creator/models/position.creator.model.ts
- src/modules/position-creator/position.creator.transaction.resolver.ts
- src/modules/position-creator/services/position.creator.compute.ts
- payment for transaction isn't put in the correct format
- added payment field for each single token model
- use the payment field for transaction generator
```
query CreatePositionSingleToken {
createPositionSingleToken(
pairAddress: <address>,
payment: {
tokenID: <token_id>,
nonce: 0,
},
) {
payment {
tokenIdentifier
tokenNonce
amount
}
swaps {
swapType
tokenInID
tokenOutID
tokenInExchangeRate
tokenInExchangeRateDenom
tokenInPriceUSD
tokenOutExchangeRate
tokenOutExchangeRateDenom
tokenOutPriceUSD
amountIn
amountOut
intermediaryAmounts
tokenRoute
fees
pricesImpact
maxPriceDeviationPercent
tokensPriceDeviationPercent
tolerance
pairs {
address
firstToken {
identifier
}
secondToken {
identifier
}
}
}
transactions {
receiver
data
value
}
}
}
```
> [MEX-466] position creator payment fix

- src/config/default.json
- not enough gas on router transactions
- update gas limits for router transactions
- N/A
> config: update gas limits for router transactions

- src/modules/router/models/filter.args.ts
- src/modules/router/services/router.service.ts
- src/modules/router/specs/router.service.spec.ts
- filter out pairs with low liqudity
- added new filter method in router service to exclude pairs with liquidity in USD below specified threshold
```
query Pairs {
pairs(offset: 0, limit: 250, minLockedValueUSD: 300) {
address
}
}
```
- query should return pairs with liquidity in USD > 300 USD
> [SERVICES-2310] filter pairs by minimum liquidityUSD

- src/services/analytics/timescaledb/timescaledb.query.service.ts
- src/services/crons/aws.query.cache.warmer.service.ts
- query total volumes for all pairs
- allow wildcard (%) pattern for series in timescaledb queries on sumDaily and sumHourly aggregates
- add queries for total pairs (pattern `erd1%`) volumes in aws cache warmer and persist in cache under key `factory`
```
query SumComplete {
sumCompleteValues(series: "factory", metric:"volumeUSD") {
timestamp
value
}
}
query Last24hSum {
values24hSum(series: "factory", metric:"volumeUSD") {
timestamp
value
}
}
```
> [SERVICES-2312] Cache warm total daily+hourly pairs volumes

- src/services/analytics/timescaledb/timescaledb.query.service.ts
- gap filling not working properly with no start date
- add check for start time to include the previous value gap fill
- N/A
> [SERVICES-2315] fix gap filling with no start date

- src/services/analytics/timescaledb/entities/timescaledb.entities.ts
- src/services/analytics/timescaledb/migration/1715251449059-xExchange.ts
- the 'where' clause has both `OR` and `AND` operators without properly grouping them 
- replace `key = 'x' OR or key = 'y'` operator with `key IN('x', 'y')` inside `where` clause for SumHourly timescaledb entity
- generate migration
- fix formatting
N/A
> [SERVICES-2355] Fix 'where' clause in SumHourly aggregate

- src/modules/auto-router/services/auto-router.transactions.service.ts
- src/modules/auto-router/specs/auto-router.service.spec.ts
- compose tasks accepts both fixed input & fixed output for router swaps
- updated composing tasks for multi pair swaps to generate transactions for both fixed input and fixed output swaps
- added multi pair swaps and unwrap EGLD composed tasks
```
query EgldSwap {
swap(
tokenInID: <token_id>,
tokenOutID: "EGLD",
amountOut: "1000000000000000000",
) {
tokenRoute
intermediaryAmounts
transactions {
data
}
}
}
```
- query should return composable task with fixed output transactions
> [MEX-414] Multi pair swap with swap function

- src/modules/tokens/models/esdtToken.model.ts
- src/modules/tokens/models/tokens.filter.args.ts
- src/modules/tokens/services/token.compute.service.ts
- src/modules/tokens/services/token.service.ts
- src/modules/tokens/services/token.setter.service.ts
- src/modules/tokens/token.resolver.ts
- src/services/analytics/interfaces/analytics.query.interface.ts
- src/services/analytics/mocks/analytics.query.service.mock.ts
- src/services/analytics/services/analytics.query.service.ts
- src/services/analytics/timescaledb/timescaledb.query.service.ts
- src/services/cache.warmer.module.ts
- src/services/crons/tokens.cache.warmer.service.ts
- token volume and previous 24h volume is needed for trending score computation
- add `previous24hVolume` field and resolver
- add getHourlySumValues timescaledb query accepting custom interval parameters
- compute volume for the 2 time windows using a single timescaledb query for the past 2 days, and splitting the results afterwards
- create tokens cache warmer cron service
```
query {
tokens(
identifiers: ["HTM-f51d55"],
) {
identifier
volumeUSD
previous24hVolume
}
}
```
> [SERVICES-2347] Token volume previous 24h

- src/config/default.json
- src/modules/position-creator/services/position.creator.transaction.ts
- src/modules/position-creator/specs/position.creator.transaction.spec.ts
- transaction generation for energy position creator used a default gas limit value
- computed energy position creator transaction gas limit based on swap routes
```
query EnergyPosition {
createEnergyPosition(
payment: {
tokenID: "EGLD",
nonce: 0,
amount: "1000000000000000000"
},
) {
transactions {
gasLimit
data
}
}
}
```
- query should return a gas limit based on default gas(10,000,000) + swapRoutes * 30,000,000
> [MEX-480] energy position creator gas limit

- src/modules/pair/models/pair.model.ts
- src/modules/pair/pair.resolver.ts
- src/modules/pair/services/pair.compute.service.ts
- compute and display % change over the past 24 hours for pair volume, fees and liquidity
- add fields and resolvers on Pair model : `previous24hLockedValueUSD`, `previous24hVolumeUSD`, `previous24hFeesUSD`
- add compute methods and caching for new fields
```
query {
filteredPairs(
filters:{
}
pagination:{
first:200
}
sorting: {
sortField:TRADES_COUNT
sortOrder:DESC
}
) {
edges {
cursor
node {
address
firstToken {
identifier
}
secondToken {
identifier
}
feesUSD24h
previous24hFeesUSD
volumeUSD24h
previous24hVolumeUSD
lockedValueUSD
previous24hLockedValueUSD
}
}
pageInfo {
startCursor
endCursor
}
pageData {
count
limit
offset
}
}
}
```
> [SERVICES-2457] Extra fields on Pair model for previous 24h data (fees, volume, liquidity)

- src/services/crons/aws.query.cache.warmer.service.ts
- running the analytics query `values24h (series: "factory", metric: "totalLockedValueUSD")` returns empy array
- add timescaleDB query for missing data in aws query cache warmer
Query below should return an array with the values for the past 24h 
```
query {
values24h (
series: "factory", 
metric: "totalLockedValueUSD"
) {
timestamp
value
}
}
```
> [SERVICES-2464] Add hourly values for global TVL from past 24h to AWS query cache warmer

- src/modules/common/page.response.ts
- the `hasPreviousPage` field of the PageInfo model on paginated queries is always false
- override the values provided by the util function `connectionFromArraySlice` from the [graphql-relay](https://github.com/graphql/graphql-relay-js) package
A paginated query (`filteredTokens` / `filteredPairs` / `filteredStakingFarms`) using forward cursor pagination like below, should correctly return `true` for the `hasPreviousPage` field 
```
query {
filters:{}
pagination:{
first:10
after:"YXJyYXljb25uZWN0aW9uOjk="
}
) {
edges {
cursor
node {
identifier
price
}
}
pageInfo {
hasNextPage
hasPreviousPage
startCursor
endCursor
}
pageData {
count
limit
offset
}
}
}
```
> [SERVICES-2466] Fix 'hasPreviousPage' field on paginated queries

- src/modules/tokens/models/tokens.filter.args.ts
- src/modules/tokens/services/token.compute.service.ts
- src/modules/tokens/services/token.service.ts
- src/services/analytics/timescaledb/timescaledb.query.service.ts
- the `previous7dPrice` field on the EsdtToken model is currently returning 0 for all tokens
- sorting by 7 days price change is required by the front-end 
- fix `getLatestCompleteValues` timescaledb query (it should use a subquery when `start` or `time` parameters are provided) 
- add compute method for price change over the last 7 days
- add sorting by the price change over 7 days to `filteredTokens` query
- Query should correctly order the tokens, and the field `previous7dPrice` should have non-zero values on core tokens 
```
query {
filters:{}
pagination:{
first:200
}
sorting: {
sortField:PRICE_CHANGE_7D
sortOrder:DESC
}
) {
edges {
cursor
node {
identifier
price
previous7dPrice
}
}
pageInfo {
startCursor
endCursor
}
pageData {
count
limit
offset
}
}
}
```
> [SERVICES-2465] Fix tokens previous 7 days price

- src/config/default.json
- src/modules/analytics/analytics.resolver.ts
- src/modules/analytics/services/analytics.aws.getter.service.ts
- src/services/analytics/timescaledb/entities/timescaledb.entities.ts
- src/services/analytics/timescaledb/migration/1718807173692-xExchange.ts
- src/services/crons/aws.query.cache.warmer.service.ts
- expose daily and hourly price analytics for pairs tokens
- allow filtering complete daily analtytics by a specific time window
- add 'firstTokenPrice' and 'secondTokenPrice' metrics to `CloseDaily` and `CloseHourly` aggregates
- generate postgres migration
- cache complete daily and 24h hourly data for pair tokens prices
- create constant for delay value used in aws query cache warmer
- enable filtering by time window on `sumCompleteValues` query
- Run migrations : `npm run typeorm:run-migrations`
- Get last 24h pair token price  :
```
query {
values24h(
series: "erd1qqqqqqqqqqqqqpgq4zafu6rzdw7fj07hjh5tkm68jsaj7hl60n4s8py4ra", 
metric:"firstTokenPrice"
) {
timestamp
value
}
}
```
- Get daily pair token price for past 7 days :
```
latestCompleteValues(
series: …
```
> [SERVICES-2468] Analytics queries improvements

- src/modules/farm/v2/services/farm.v2.compute.service.ts
- src/modules/pair/services/pair.compute.service.ts
- src/modules/pair/specs/pair.compute.service.spec.ts
- src/modules/router/models/filter.args.ts
- src/modules/router/services/router.service.ts
- src/submodules/weekly-rewards-splitting/services/weekly-rewards-splitting.compute.service.ts
- allow the result of `filteredPairs` query to be sorted by compoundedAPR
- add sorting by compounded APR to filteredPairs query
```
query CompoundedAPR {
filteredPairs(
filters:{}
pagination:{
first:200
}
sorting: {
sortField:APR
sortOrder:DESC
}
) {
edges {
cursor
node {
address
firstToken {
identifier
}
secondToken {
identifier
}
compoundedAPR{
feesAPR
farmBaseAPR
farmBoostedAPR
dualFarmBaseAPR
dualFarmBoostedAPR
}
}
}
pageInfo {
startCursor
endCursor
}
pageData {
count
limit
offset
}
}
}
```
> [SERVICES-2469] Sorting pairs by APRs

- src/modules/locked-asset-factory/models/locked-asset.model.ts
- src/modules/locked-asset-factory/services/locked-asset.service.ts
- src/modules/locked-asset-factory/specs/locked.asset.service.spec.ts
- currently `UnlockMileStoneModel` only exposes epochs left until the unlock
- add `unlockEpoch` field to `UnlockMileStoneModel` 
```
query {
decodeLockedAssetAttributes(args: {
batchAttributes:[{
identifier:"LKMEX-aab910-47ec8a",
attributes:"AAAAAgAAAAAAAASyAAAAAAAAw1AAAAAAAAAE0AAAAAAAAMNQAA=="
}]
}) {
unlockSchedule {
epochs
percent
unlockEpoch
}
}
}
```
> [SERVICES-2475] Add unlock epoch to unlockSchedule

- src/modules/staking-proxy/models/staking.proxies.response.ts
- src/modules/staking-proxy/models/staking.proxy.args.model.ts
- src/modules/staking-proxy/services/staking.proxy.filtering.service.ts
- src/modules/staking-proxy/services/staking.proxy.service.ts
- src/modules/staking-proxy/specs/staking.proxy.transaction.service.spec.ts
- src/modules/staking-proxy/staking.proxy.module.ts
- src/modules/staking-proxy/staking.proxy.resolver.ts
- src/modules/user/specs/user.energy.compute.service.spec.ts
- provide a [Relay](https://relay.dev/)-compliant query for fetching staking proxies data
- create new `filteredStakingProxies` query that follows the GraphQL "Connections" specification
- add staking farms filtering service (wildcard filtering by a token + filtering by address / LP farm address / staking farm address / pair address)
- 
```
query {
filteredStakingProxies(
filters: {
searchToken: "UTK"
address: "erd1qqqqqqqqqqqqqpgqqwn0qa7ft4tew05r0zcd0c5hay5mp6np0n4ss8jm86"
stakingFarmAddress: "erd1qqqqqqqqqqqqqpgquvklwltnlgyn5w5cd65ey36nw8sc008d0n4s0xpr25"
pairAddress: "erd1qqqqqqqqqqqqqpgq4zafu6rzdw7fj07hjh5tkm68jsaj7hl60n4s8py4ra"
lpFarmAddress: "erd1qqqqqqqqqqqqqpgql7rysqgxxzhykg3j6vccnx4003z2mcl80n4ste3jh8"
}
pagination: { first: 200 }
) {
edges {
cursor
node {
address
lpFarmAddress …
```
> [SERVICES-2474] Filtered staking proxies query implementing "Connections" spec

- src/modules/analytics/analytics.resolver.ts
- src/modules/analytics/services/analytics.compute.service.ts
- src/modules/auto-router/services/auto-router.service.ts
- src/modules/energy/services/energy.service.ts
- src/modules/farm/base-module/services/farm.base.service.ts
- src/modules/fees-collector/services/fees-collector.compute.service.ts
- src/modules/governance/services/governance.service.ts
- src/modules/locked-asset-factory/services/locked.asset.getter.service.ts
- src/modules/pair/services/pair.service.ts
- src/modules/price-discovery/services/price.discovery.service.ts
- src/modules/proxy/services/proxy.service.ts
- src/modules/rabbitmq/handlers/pair.liquidity.handler.service.ts
- src/modules/staking-proxy/services/staking.proxy.service.ts
- src/modules/staking/services/staking.compute.service.ts
- src/modules/staking/services/staking.service.ts
- src/modules/tokens/mocks/token.service.mock.ts
- src/modules/tokens/services/token.service.ts
- src/modules/tokens/services/token.setter.service.ts
- src/modules/tokens/specs/token.service.spec.ts
- src/modules/wrapping/services/wrap.service.ts
- src/services/crons/tokens.cache.warmer.service.ts
- src/submodules/weekly-rewards-splitting/services/weekly-rewards-splitting.compute.service.ts
- currently the TTL for existing cached token metadata is simply extended on request. A refetch of the data is only performed if the value is not present in cache 
- add method for maintaining token metadata in cache warmer
- remove logic that extends TTL for values present in cache
```
query {
filters: { identifiers: ["WEGLD-a28c59"] }
pagination: { first: 200 }
sorting: { sortField: TRENDING_SCORE, sortOrder: DESC }
) {
edges {
cursor
node {
identifier
volumeUSD24h
price
circulatingSupply
}
}
pageInfo {
startCursor
endCursor
}
pageData {
count
limit
offset
}
}
}
```
> [SERVICES-2485] Update caching strategy for tokens metadata

- src/modules/pair/models/pair.model.ts
- src/modules/pair/pair.module.ts
- src/modules/pair/pair.resolver.ts
- src/modules/pair/services/pair.compute.service.ts
- expose token rewards on the Pair model
- add `PairRewardTokensModel` with field resolvers
- add `rewardTokens` field to `PairModel`
- On `filteredPairs` query : 
```
query {
filteredPairs(filters: {}, pagination: { first: 200 }) {
edges {
cursor
node {
address
rewardTokens {
poolRewards {
identifier
assets {
svgUrl
}
}
farmReward {
collection
assets {
svgUrl
}
}
dualFarmReward {
identifier
assets {
svgUrl
}
}
}
}
}
pageInfo {
startCursor
endCursor
}
pageData {
count
limit
offset
}
}
}
```
> [SERVICES-2488] Token rewards information for pool

- src/modules/pair/pair.resolver.ts
- src/modules/staking/services/staking.compute.service.ts
- src/modules/user/services/userEnergy/user.energy.compute.service.ts
- negative energy query returns false positive
- wrong values for `dualFarmBaseAPR` field of PairCompoundedAPR model
- 
- return `false` on negative energy query when no locked tokens are present
- add stake farm base APR compute method + use it in Pair compounded APR field resolver 
- `userNegativeEnergyCheck` query should return false when there're no locked tokens of a certain type
> [SERVICES-2495] Fix negative energy query + dual farms base apr computation

- src/helpers/decorators/caching.decorator.ts
- src/modules/farm/base-module/services/farm.setter.service.ts
- src/modules/pair/services/pair.setter.service.ts
- src/modules/router/services/router.service.ts
- src/modules/staking/services/staking.setter.service.ts
- src/modules/tokens/services/token.setter.service.ts
- src/modules/tokens/specs/token.service.spec.ts
- src/services/cache.warmer.module.ts
- src/services/caching/cache.ttl.info.ts
- src/services/crons/farm.cache.warmer.service.ts
- src/services/crons/pair.cache.warmer.service.ts
- src/services/crons/staking.cache.warmer.service.ts
- src/services/crons/tokens.cache.warmer.service.ts
- src/services/generics/generic.setter.service.ts
- src/utils/cache.utils.ts
- high cache miss rate on pair field resolvers 
- cache `undefined` and `null` values in `GetOrSet` decorator, as well as GenericSetter (cache) service 
- add more fields to pairs, tokens, farms and staking cache warmers
- N/A
> [SERVICES-2513] Caching optimizations

- src/modules/farm/models/farm.v2.model.ts
- src/modules/farm/v2/farm.v2.resolver.ts
- src/modules/farm/v2/services/farm.v2.abi.service.ts
- src/modules/staking/models/staking.model.ts
- src/modules/staking/services/staking.abi.service.ts
- src/modules/staking/staking.resolver.ts
- missing information for farm and staking contracts
- added methods to get farm token supply for week from farms and staking contracts
- added field resolvers for farm token supply for current week on farms and staking resolvers
```
query Stakings {
stakingFarms {
address
farmTokenSupplyCurrentWeek
}
}
```
- query should return value on staking boosted rewards contracts
> [MEX-494] farm token supply for week

- src/modules/farm/v2/services/farm.v2.transaction.service.ts
- src/modules/proxy/services/proxy-farm/proxy.farm.transactions.service.ts
- src/modules/staking/services/staking.transactions.service.ts
- on testing environments the nfts count for user returns 0
- use default value for nfts count for user
- N/A
> [MEX-495] Fix total farm position migrations transactions

- src/modules/trading-view/services/trading.view.service.ts
- src/services/analytics/interfaces/analytics.query.interface.ts
- src/services/analytics/mocks/analytics.query.service.mock.ts
- src/services/analytics/services/analytics.query.service.ts
- src/services/analytics/timescaledb/timescaledb.query.service.ts
- there's currently no check for the start of activity on a pair / token when returning `nextTime` on empty intervals. This causes the library to perform a series of requests (+30) before initial render
- compare request `start` parameter with the series start date before returning `nextTime` in intervals without data (signals to the frontend TV library that there are no more candles in the past) 
- N/A
> [SERVICES-2525] Fix for candlesticks response next time

- src/config/default.json
- src/modules/tokens/services/token.compute.service.ts
- weights used in formula are hardcoded in the tokens compute service
- add weights used in formula to config + remove hardcoded values
- N/A
> [SERVICES-2524] Update token trending score formula

- src/modules/user/services/userEnergy/user.energy.compute.service.ts
- metabonding energy for user returns default value if no tokens staked
- check for valid staked token nonce on metabonding negative energy check
```
query NegativeEnergyCheck {
userNegativeEnergyCheck {
metabonding
}
}
```
- query should not return error if no tokens staked in metabonding staking sc
> [MEX-496] fix metabonding negative energy check

- src/modules/pair/models/pair.model.ts
- src/modules/pair/pair.resolver.ts
- exposing the farm address and staking proxy address on the Pair model would reduce the number of needed queries on the `Create position` page
- expose `farmAddress` and `stakingProxyAddress` fields on the Pair model
```
query {
filteredPairs(
filters: {}
pagination: { first: 100 }
sorting: { sortField: TVL, sortOrder: DESC }
) {
edges {
cursor
node {
address
firstToken {
name
identifier
}
secondToken {
name
identifier
}
farmAddress
stakingProxyAddress
}
}
pageInfo {
startCursor
endCursor
}
pageData {
count
limit
offset
}
}
}
```
> [SERVICES-2532] Expose extra fields on pair model

- src/services/analytics/timescaledb/timescaledb.query.service.ts
- missing data on queries where default gap filling was removed (more obvious on pairs/tokens with low activity)
- perform a separate query with a fixed time window (more performant) for gap filling
- N/A
> [SERVICES-2530] Gap filling query with time constraints

- src/modules/analytics/analytics.module.ts
- src/modules/router/router.module.ts
- src/modules/router/router.resolver.ts
- src/modules/router/services/router.compute.service.ts
- src/modules/router/services/router.setter.service.ts
- compute total volumes for 24h takes too long when no value is cached
- use data from analytics cached values for volumes to compute total volumes in 24h
```
query Factory {
factory {
totalVolumeUSD24h
}
}
```
- query should return value when the cron job finished to refresh the volumes
> [MEX-497] use cached data to compute totalVolumeUSD24h

- src/modules/farm/farm.factory.ts
- src/modules/farm/farm.query.resolver.ts
- src/modules/farm/models/farm.args.ts
- filter farms by address and version
- added filtering on farms based on version and farm address
```
query farmsPageDataQuery {
farms(
filters: {
versions: ["v1.2", "v2"],
addresses: [
<farm_address>
]
}
) {
...on FarmModelV1_2 {
address
version
}
...on FarmModelV1_3 {
address
version
}
...on FarmModelV2 {
address
version
}
}
}
```
- query should return filtered farms
> [MEX-498] Add filtering of farms query

- src/config/shadowfork2.json
- too few trades on battlenet affects computed trending score for tokens
- add trending score config values to battlenet config
- reduce trades count weight to 0
- N/A
> SERVICES-2538: add trending score config for battlenet

- src/config/default.json
- src/config/index.ts
- src/modules/energy/energy.module.ts
- src/modules/energy/energy.resolver.ts
- src/modules/energy/models/energy.model.ts
- src/modules/energy/services/energy.compute.service.ts
- src/modules/energy/services/energy.service.ts
- src/modules/fees-collector/specs/fees.collector.compute.service.spec.ts
- move user energy league information to xExchange backend
- added new user energy model
- added energy leagues information
- added computation for energy league
- added resolver for user energy model
```
query {
userEnergy {
amount
lastUpdateEpoch
totalLockedTokens
league
}
}
```
- query should return league for user energy
> [MEX-503] user energy league

- src/modules/pair/pair.resolver.ts
- src/modules/pair/services/pair.compute.service.ts
- src/modules/staking/services/staking.compute.service.ts
- src/modules/staking/services/staking.setter.service.ts
- src/modules/staking/staking.resolver.ts
- src/services/crons/staking.cache.warmer.service.ts
- compute staking total value locked in USD was wrong
- staking APR should be 0 if no rewards are distributed
- fixed computing for staking total value locked in USD
- added checks for computing staking APR to return 0 in case no rewards are distributed
- removed unnecessary caching from staking compute service
```
query FilteredStaking {
filteredStakingFarms(
filters: {
searchToken: ""
}
sorting: {
sortField: TVL
sortOrder: DESC
}
) {
edges {
node {
address
farmToken {
collection
}
produceRewardsEnabled
apr
boostedApr
}
}
}
}
```
> [MEX-502] fixes on staking module

- src/config/default.json
- src/modules/tokens/services/token.compute.service.ts
- trending score isn't performing right on edge cases
- added minimum score to be used in case of edge cases on token metrics changes
```
query Tokens {
pagination: {
first: 200
}
filters: {
enabledSwaps: false
}
sorting: {
sortField: TRENDING_SCORE
sortOrder: DESC
}
) {
edges {
node {
identifier
trendingScore
}
}
}
}
```
> [MEX-505] Fix token trending score

- src/services/analytics/timescaledb/timescaledb.query.service.ts
- the query performed in cases where manual gapfilling is needed has poor performance on series without any activity (+3s)
- make a single query for fetching start dates for all series
- N/A
> [SERVICES-2533] Improve fetching series start date performance in timescaledb

- src/services/analytics/timescaledb/timescaledb.query.service.ts
- query for fetching all series start dates has poor performance
- run query on close `close_daily` aggregate instead of `hyper_dex_analytics` table
- N/A
> [SERVICES-2548] Fix timescaledb query for fetching all series start date

- src/modules/pair/services/pair.filtering.service.ts
- src/modules/router/models/filter.args.ts
- src/modules/router/services/router.service.ts
- src/modules/router/specs/router.service.spec.ts
- src/modules/staking-proxy/models/staking.proxy.args.model.ts
- src/modules/staking-proxy/services/staking.proxy.filtering.service.ts
- src/modules/user/models/user.model.ts
- src/modules/user/services/esdt.compute.service.ts
- src/modules/user/services/metaEsdt.compute.service.ts
- src/modules/user/specs/user.service.spec.ts
- ease the association for multiple user positions to specific pair
- added pair address field for user lp tokens and user nfts positions that can be associated with a pair address
- updated filtering on filtered queries to use arrays of addresses
```
query UserNfts {
userNfts {
userLockedTokenEnergy {
collection
name
identifier
}
userFarmToken {
collection
valueUSD
pairAddress
}
userDualYieldToken {
collection
valueUSD
pairAddress
}
userLockedSimpleFarmToken{
collection
pairAddress
}
userStakeFarmToken {
collection
valueUSD
creator
}
userUnbondFarmToken {
collection
creator
}
}
}
```
- query should return an pair address associated with the user position
> [MEX-507] user positions extra information

- src/modules/analytics/services/analytics.aws.getter.service.ts
- by default the query returns 25 data points starting with the last 24h ago
- display the latest 24 data points for hourly analytics charts
- return the latest 24 data points for hourly analytics charts
- N/A
> [MEX-508]: return 24 data points on analytics

- src/helpers/decorators/caching.decorator.ts
- src/modules/farm/specs/farm.compute.service.spec.ts
- src/utils/metrics.collector.ts
- load testing revealed a constant high number of requests to the remote cache
- if value is present in remote cache, set it in local cache before returning it
- add extra cache metrics (remote/local cache hit, remote cache miss)
- N/A
> [SERVICES-2575] Fix local cache misses

- src/modules/farm/mocks/farm.v2.abi.service.mock.ts
- src/modules/farm/models/farm.model.ts
- src/modules/farm/specs/farm.v2.compute.service.spec.ts
- src/modules/farm/v2/farm.v2.module.ts
- src/modules/farm/v2/farm.v2.resolver.ts
- src/modules/farm/v2/services/farm.v2.compute.service.ts
- src/modules/farm/v2/services/farm.v2.service.ts
- src/modules/farm/v2/services/interfaces.ts
- src/modules/staking/models/staking.model.ts
- src/modules/staking/services/staking.compute.service.ts
- src/modules/staking/services/staking.service.ts
- src/modules/staking/staking.module.ts
- src/modules/staking/staking.resolver.ts
- move compute for user current boosted APR and maximum boosted APR in backend side
- added new fields `currentBoostedAPR` and `maximumBoostedAPR` for `BoostedRewardsModel`
- updated computes methods in farm and staking for current and maximum boosted APR specific for users
- added options to put arbitrary values for user farm amount and energy to compute APRs
```
query StakingBoostedRewards {
stakingAddresses: [
"erd1qqqqqqqqqqqqqpgqcedkmj8ezme6mtautj79ngv7fez978le2jps8jtawn"
]
) {
curentBoostedAPR(
additionalUserFarmAmount: <amount(can be negative)>
additionalUserEnergy: <amount(can be negative)>
)
maximumBoostedAPR(
additionalUserFarmAmount: <amount(can be negative)>    
)
}
}
```
> [MEX-514] compute user boosted apr

- src/modules/analytics/services/analytics.aws.getter.service.ts
- src/modules/pair/services/pair.abi.loader.ts
- src/modules/pair/services/pair.compute.loader.ts
- src/modules/pair/services/pair.filtering.service.ts
- src/modules/pair/services/pair.service.ts
- src/modules/router/services/router.service.ts
- the `pairs` and `filteredPairs` queries rely on Promise.all() for getting field data needed for sorting and filtering. Although most data is coming from cache, this still causes degradation in performance due to the large number of pairs
- add pairs bulk getter methods for the following fields : `lpTokenID`, `state`, `feeState`, `lockedValueUSD`, `deployedAt`, `tradesCount`, `hasFarms`, `hasDualFarms`
- refactor pair dataloaders to use bulk getter methods
- refactor pairs filtering and sorting to use bulk getters
- N/A
> [SERVICES-2569] Caching improvements for pairs

- src/public.app.module.ts
- src/utils/logging.interceptor.ts
- src/utils/query.metrics.plugin.ts
- query metrics didn't take into account the execution for each field resolver
- added a graphql plugin to measure the full query execution time including the filed resolvers
- N/A
> [MEX-515] Add query metrics plugin for apollo server

- src/modules/pair/services/pair.compute.service.ts
- src/modules/staking/services/staking.transactions.service.ts
- migrate staking positions transactions should not include unbonding tokens
- added check to exclude unbonding tokens from migrate staking positions transactions
- N/A
> [MEX-495] fix migrate staking positions transactions

- src/modules/staking/models/staking.args.ts
- src/modules/staking/services/staking.abi.service.ts
- src/modules/staking/services/staking.filtering.service.ts
- src/modules/staking/services/staking.service.ts
- The front-end needs a way to filter out staking farms with depleted rewards on the `filteredStakingFarms` query
- add `rewardsDepleted` boolean filter to `filteredStakingFarms` query
- the query below should only return staking farms with remaining rewards
```
query {
filteredStakingFarms(
filters:{
rewardsDepleted: false
}
pagination:{
first:1
}
sorting: {
sortField: TVL
sortOrder: DESC
}
) {
edges {
cursor
node {
address
apr
farmingToken {
identifier
}
farmToken {
ticker
}
}
}
pageData {
count
limit
offset
}
}
}
```
> [SERVICES-2577] Staking farms filter by depleted rewards

- src/modules/tokens/services/token.compute.service.ts
- src/modules/tokens/services/token.filtering.service.ts
- src/modules/tokens/services/token.loader.ts
- src/modules/tokens/services/token.service.ts
- the `tokens` and `filteredTokens` queries rely on Promise.all() for getting field data needed for sorting and filtering. Although most data is coming from cache, this still causes degradation in performance due to the large number of tokens
- add bulk getter methods in tokens.compute service
- refactor tokens filtering and sorting to use bulk methods
- refactor token dataloaders to use bulk methods
- N/A
> [SERVICES-2578] Caching improvements for tokens queries

- src/modules/farm/base-module/services/farm.abi.loader.ts
- src/modules/farm/base-module/services/farm.base.service.ts
- src/modules/farm/base-module/services/farm.compute.loader.ts
- src/modules/pair/services/pair.abi.loader.ts
- src/modules/pair/services/pair.compute.loader.ts
- src/modules/pair/services/pair.service.ts
- src/modules/tokens/services/token.compute.service.ts
- src/modules/tokens/services/token.loader.ts
- src/modules/tokens/services/token.service.ts
- src/utils/get.many.utils.ts
- values fetched from remote cache are not updated in local cache
- add `ttlOptions` parameter to `getAllKeys` function and use it to set local cache if needed
- N/A
> [SERVICES-2582] Set local cache in getAllKeys utility function

- src/services/crons/analytics.cache.warmer.service.ts
- src/services/crons/pair.cache.warmer.service.ts
- the delay between timescaledb queries performed in cache warmers is a hardcoded value
- use delay value in config
- N/A
> [SERVICES-2584] Update cache warmer delay to config value

- src/modules/staking/services/staking.compute.service.ts
- user boosted APR for stakings that doesn't produce rewards should be 0
- add check for produce rewards in compute user boosted APR
- N/A
> [MEX-514] return 0 APR for stakings with no rewards

- src/modules/staking-proxy/models/staking.proxy.model.ts
- src/modules/staking-proxy/services/staking.proxy.service.ts
- src/modules/staking-proxy/staking.proxy.resolver.ts
- Currently, the front end needs to perform an additional query for fetching` minUnbondEpochs` for a staking farm corresponding to a staking proxy
- add `stakingMinUnboundEpochs` field to StakingProxy model 
- add resolver method for the newly added field
```
stakingProxies {
address
stakingFarmAddress
stakingMinUnboundEpochs
farmToken {
ticker
}
lpFarmToken {
ticker
}
}
```
> [SERVICES-2586] Add staking min unbound epochs field to staking proxy model

- src/modules/pair/pair.resolver.ts
- src/modules/staking/services/staking.compute.service.ts
- dual farm boosted APR reported on pair model isn't the maximum value that can be achieved
- added new method to compute maximum boosted APR for staking contracts
- updated dual farm boosted APR from pair model to use maximum boosted APR from staking
- N/A
> [SERVICES-2416] use maximum boosted APR for pair dual farm APR

- src/modules/farm/v2/services/farm.v2.compute.service.ts
- src/modules/staking/services/staking.compute.service.ts
- if user doesn't have any total staked amount registered, the query would return an error for non-nullable field
- if user doesn't have any total farm amount registered, the query would return an error for non-nullable field
- check for user total staked amount when computing boosted APR for staking
- check for user total farm amount when computing boosted APR for farms
```
query StakingBoostedRewards {
stakingAddresses: [
<staking_address>
]
) {
curentBoostedAPR
maximumBoostedAPR
}
}
```
- query should return 0 for both fields if no total staked amount for user
> [MEX-514] fix compute user APR if no total staked amount

- src/modules/farm/specs/farm.v2.compute.service.spec.ts
- src/modules/farm/v2/services/farm.v2.compute.service.ts
- src/modules/staking/services/staking.compute.service.ts
- src/modules/user/user.info-by-week.resolver.ts
- on farms & stakings accumulated rewards should be used to get the boosted accumulated rewards
- changed the view method to get accumulated rewards on both farms & stakings to use `accumulatedRewardsForWeek`
- small refactor on `computeUserRewardsForWeek` method
```
query FarmBoostedRewards {
getFarmBoostedRewardsBatch(
farmsAddresses: [<farm_address>, ...]
) {
}
}
```
```
query StakingBoostedRewards {
stakingAddresses: [<staking_address>, ...]
) {
}
}
```
- both queries should return accumulating rewards for current week
> [MEX-517] fix user accumulated rewards

- src/modules/pair/models/pair.model.ts
- src/modules/pair/pair.module.ts
- src/modules/pair/pair.resolver.ts
- src/modules/pair/services/pair.compute.loader.ts
- src/modules/pair/services/pair.compute.service.ts
- src/modules/pair/services/pair.filtering.service.ts
- src/modules/pair/services/pair.metadata.builder.ts
- src/modules/pair/services/pair.setter.service.ts
- src/modules/router/models/filter.args.ts
- src/modules/router/services/router.service.ts
- src/services/crons/pair.cache.warmer.service.ts
- src/services/elastic-search/services/es.transactions.service.ts
- front end requires information regarding pair swaps performed in the last 24 hours
- add `tradesCount24h` field to Pair model + resolver method
- refactor compute method for 'tradesCount' to use ESTransactions service
- add bulk get method and dataloader for the new field 
- add new field to pair cache warmer
- add sorting and filtering by tradesCount24h to `filteredPairs` query
- Running the query below should return only the pairs with more than 30 trades performed in the last 24 hours 
```
query  {
filteredPairs(
filters: {
minTradesCount24h: 30
}, 
pagination: { first: 20 }, 
sorting: {
sortField:TRADES_COUNT_24, 
sortOrder:DESC
}
) {
edges {
cursor
node {
address
firstToken { identifier }
secondToken { identifier }
tradesCount
tradesCount24h
}
}
}
}
```
> [SERVICES-2600] Add Pair field for trades count in the past 24 hours

- src/modules/auth/native.auth.guard.ts
- validation for impersonate address is done using the request headers instead of optional arguments from native auth token
- removed optional validation method for impersonate address
- N/A
> [MEX-519] remove optional validation method from native auth guard

- src/config/default.json
- remove minimum swap amount from trade modal
- updated `MIN_SWAP_AMOUNT` to `0`
- N/A
> [MEX-520] Remove min swap amount

- src/modules/locked-asset-factory/locked-asset.resolver.ts
- src/modules/locked-asset-factory/services/transaction-locked-asset.service.ts
- src/modules/simple-lock/services/simple.lock.transactions.service.ts
- src/modules/simple-lock/transaction.resolver.ts
- src/services/multiversx-communication/mx.proxy.service.ts
- use SmartContractTransactionsFactory for generating transactions for Locked Asset Factory, Simple Lock SCs
- update TransactionsLockedAssetService methods
- update SimpleLockTransactionService methods
- add sender parameter where needed + update resolver methods
- N/A
> [SERVICES-2632] Update transaction generation for Locked Asset Factory, Simple Lock SCs

- src/modules/fees-collector/services/fees-collector.setter.service.ts
- src/modules/staking/services/staking.setter.service.ts
- src/services/cache.warmer.module.ts
- src/services/crons/fees.collector.cache.warmer.service.ts
- src/services/crons/staking.cache.warmer.service.ts
- Fees collector generic contract state is computed on request on portfolio queries
- add fees collector cache warmer
- cache warm staking `boostedYieldsFactors`
- N/A
> [SERVICES-2596] Fees collector cache warmer + update staking cache warmer

- src/modules/analytics/services/analytics.aws.getter.service.ts
- src/modules/tokens/services/token.compute.service.ts
- `previous24hPrice` field on token model is 0 when data is missing in timescaledb hourly aggregate (tokens with no activity)
- compute previous 24h price using the price of WEGLD
```
query {
filters: {}
pagination: { first: 400 }
sorting: { sortField: PREVIOUS_24H_PRICE, sortOrder: ASC }
) {
edges {
cursor
node {
identifier
price
previous24hPrice
}
}
}
}
```
> [SERVICES-2644] Fix token previous 24h price

- src/modules/staking/models/staking.model.ts
- src/modules/staking/services/staking.compute.service.ts
- src/modules/staking/staking.resolver.ts
- expose values for staking APR and rewards remaining days if not capped by max APR
- add `aprIfUncapped` and `rewardsRemainingDaysIfUncapped` fields to Staking model 
- add field resolvers and compute methods
- small refactor to remove duplicate code
```
query {
filteredStakingFarms(filters: {}, pagination: { first: 200 }) {
edges {
node {
address
farmingToken {
identifier
}
apr
aprIfUncapped
rewardsRemainingDays
rewardsRemainingDaysIfUncapped
}
}
}
}
```
> [SERVICES-2651] Add extra fields to staking model

- src/modules/auto-router/services/auto-router.transactions.service.ts
- multi pair swap endpoint require a variadic type
- wrap the multi pair swap arguments into a variadic value
```
query Swap {
swap(
amountIn: "1000000",
tokenInID: "USDC-c76f1f",
tokenOutID: "MEX-455c57",
tolerance: 0.001
) {
transactions {
receiver
value
data
gasLimit
}
}
}
```
> [MEX-522] fix type on multi pair swap transaction

- src/config/devnet.json
- necessary for some cleanup related to Hatom's devnet test environment
- remove farm SC address from devnet config
- N/A
> [SERVICES-2706] Remove hatom farm address from devnet config

- src/modules/staking/services/staking.compute.service.ts
- src/modules/user/services/userEnergy/user.energy.compute.service.ts
- src/modules/user/specs/user.energy.compute.service.spec.ts
- the `userOutdatedContracts` query always returns a result for positions in staking farms where the rewards have stopped
- add early exit if the contract is not producing rewards in the compute method for outdated staking contracts 
- fix `isProducingRewards` method and usage in staking compute  
- add caching to `isProducingRewards` method
- the query should not return a result if the user has a position in a staking farm that is no longer producing rewards
```
query {
userOutdatedContracts {
address
type
claimProgressOutdated
farmToken 
}
}
```
> [SERVICES-2682] Fix staking outdated contracts

- src/modules/pair/interfaces.ts
- src/modules/pair/mocks/pair.compute.service.mock.ts
- src/modules/pair/mocks/pair.service.mock.ts
- src/modules/pair/pair.resolver.ts
- src/modules/pair/services/pair.abi.loader.ts
- src/modules/pair/services/pair.compute.loader.ts
- src/modules/pair/services/pair.compute.service.ts
- src/modules/pair/services/pair.filtering.service.ts
- src/modules/pair/services/pair.setter.service.ts
- src/modules/router/services/router.service.ts
- src/modules/router/specs/router.service.spec.ts
- src/modules/tokens/services/token.loader.ts
- src/services/crons/pair.cache.warmer.service.ts
- src/utils/get.many.utils.ts
- using falsy checks instead of explicit undefined checks inside the cache `getAllKeys` method triggers unnecessary individual redis GET requests for cached booleans / the number 0
- LP tokens metadata is only being cached on request resulting in slow queries for the first user that needs the data
- dataloaders have a default in-memory cache enabled
- disable caching for pair (abi + compute) and tokens dataloaders
- add dataloader for pair 24h volume
- cache warm LP tokens metadata
- replace falsy check with explicit undefined check in `getAllKeys` util function
- N/A
> [SERVICES-2691] Performance improvements and caching fixes

- src/helpers/proxy.network.provider.profiler.ts
- src/modules/auto-router/specs/auto-router.service.spec.ts
- src/modules/farm/v2/services/farm.v2.abi.service.ts
- src/modules/fees-collector/services/fees-collector.compute.service.ts
- src/modules/router/services/router.transactions.service.ts
- src/modules/staking/services/staking.abi.service.ts
- src/modules/user/specs/user.energy.transaction.service.spec.ts
- src/services/multiversx-communication/mx.api.service.ts
- src/services/multiversx-communication/mx.proxy.service.ts
- missing unit tests for multi-swap and update farms energy transactions
- latest version of network providers print a warning to console if `clientName` parameter is omitted
- add unit tests for update farms energy transaction
- add unit test for multi-swap transaction
- add `clientName` to proxy and api network providers
- N/A
> [SERVICES-2660] Add missing unit tests for transaction generation

- src/services/crons/pair.cache.warmer.service.ts
- for newly created pairs the lp token metadata doesn't exist and the cron job would always refresh the first value which is undefined
- use the raw method to get the lp token metadata every time the cron job refreshes the value
- N/A
> [MEX-528] fix lp token metadata refresh

- src/config/default.json
- src/config/devnet.json
- src/config/staging.json
- src/modules/farm/models/farm.model.ts
- src/modules/pair/services/pair.compute.service.ts
- src/utils/farm.utils.ts
- deployed new MEX/EGLD farm
- current MEX/EGLD farm will be deprecated
- added `deprecated` farm type for v2 farm models
- updated pair compute methods to use only active v2 farm addresses
```
query farmsPageDataQuery {
farms(
filters: {
versions: ["v2"]
}
) {
...on FarmModelV2 {
address
farmToken {
collection
}
rewardType
}
}
}
```
- query should return `deprecated` for current MEX/EGLD farm reward type
> [MEX-532] deprecated farm type

- src/modules/farm/v2/services/farm.v2.compute.service.ts
- `curentBoostedAPR` computation for farm positions is not increasing when `additionalUserEnergy` is provided
- add `additionalUserEnergyAmount` to user energy when computing user rewards for week
```
query {
getFarmBoostedRewardsBatch(
farmsAddresses: [
"erd1qqqqqqqqqqqqqpgqapxdp9gjxtg60mjwhle3n6h88zch9e7kkp2s8aqhkg",
]
) {
farmAddress
curentBoostedAPR(
additionalUserEnergy: "1000000000000000000000000000000"
)
}
}
```
> [MEX-533] Fix farm user rewards for week

- src/config/default.json
- missing gas limits configs for deprecated farm type
- added missing gas limits config into default config file
```
query ExitFarm {
exitFarm(
farmAddress: "erd1qqqqqqqqqqqqqpgqqjpfmappkpzq6kdju3mkqepk3d2kcymu0n4srd45sa",
farmTokenID: "EGLDMEXFL-2ed783",
farmTokenNonce: 60,
amount: "2452220725944649483",
exitAmount: "2452220725944649483"
) {
gasLimit
data
}
}
```
- query should return transaction
> [MEX-532] added gas config for deprecated farm type

- src/config/mainnet.json
- new MEX/EGLD farm deployed
- move current MEX/EGLD farm to deprecated
- add new MEX/EGLD farm address on mainnet config
- N/A
> [MEX-532] Update current MEX/EGLD farm type to deprecated

- src/modules/user/services/userEnergy/user.energy.compute.service.ts
- user outdated contracts were added to the list even though the contract was not producing rewards anymore
- it should not be an outdated contract if there are no rewards being produced and the total rewards distributed in the current claim progress week for user is `0`
- added a check for the total rewards distributed for the user current claim progress
```
query UserOutdatedContracts {
userOutdatedContracts {
address
type
farmToken
claimProgressOutdated
}
}
```
- query should not include contracts with stopped rewards for which user already claimed all the rewards
> [MEX-650] Fix user outdated contracts when no rewards are produced

- src/modules/user/services/userEnergy/user.energy.compute.service.ts
- Cannot read properties of undefined (reading 'amount')
- added check for length of `claimProgressTotalRewards` array
- N/A
> [MEX-650] Fix undefined amount in compute outdated contracts

- src/services/crons/aws.query.cache.warmer.service.ts
- current implementation does not provide flexibility to choose which pairs are taken into account for total value locked chart from analytics
- compute total value locked in USD value over 24h and complete values using all the data points from each pair
- added logic inside `updateHistoricTokensData` method to store all the pairs data and use them for compute
- N/A
> [MEX-658] fix analytics total value locked

- src/config/default.json
- src/modules/pair/services/pair.compute.loader.ts
- src/modules/pair/services/pair.compute.service.ts
- src/modules/tokens/services/token.compute.service.ts
- src/services/crons/aws.query.cache.warmer.service.ts
1.  Skewed TVL and ranking for tokens and pairs (due to pairs containing tokens with a high supply and low liquidity)
2.  Displayed Total locked value on analytics is sometimes wrong (too small) at the beginning of each hour. This happens because the `start` and `end` dates used in the queries will differ at the benning of an hour
- (1) fix compute methods for pairs and tokens locked value by comparing the difference between the 2 tokens. If the difference exceeds a threshold of `1000000` only use the smallest value
- (1) add bulk get methods for pair first and second tocken locked values + update pair dataloader
- (2) increase cron time for `updateHistoricPairsData` and decrease query cache warmer delay value
- N/A
> [MEX-663] Fix tokens liquidity

- src/modules/analytics/analytics.module.ts
- src/modules/analytics/analytics.resolver.ts
- src/modules/analytics/models/trading.activity.model.ts
- src/modules/analytics/services/analytics.compute.service.ts
- src/modules/analytics/services/analytics.setter.service.ts
- src/services/crons/analytics.cache.warmer.service.ts
- src/services/elastic-search/services/es.events.service.ts
- Fetching Swap Transactions from the REST API didn't catch all required transactions correctly
- New Endpoint for retrieving Trading Activity for both Tokens and Pairs
- Using Events Index to catch all transactions
Replace "erd1qqqqqqqqqqqqqpgq5jnjpsukhl295ry3wjrd3gtff0amrgux2jpsz3reum" with any other pair address or token Identifier
```
tradingActivity(series: "erd1qqqqqqqqqqqqqpgq5jnjpsukhl295ry3wjrd3gtff0amrgux2jpsz3reum") {
hash,
timestamp,
action,
inputToken {
amount,
tokenIdentifier,
tokenNonce
},
outputToken {
amount,
tokenIdentifier,
tokenNonce
}
}
```
> [ MEX-662 ] Trading activity for Tokens and Pairs

- src/modules/analytics/services/analytics.compute.service.ts
- If there are no events generated for a token, filteredEvents array will be empty
- early exit from while loop if no more iterations are needed
- on the cache warmer instance it should not be any `undefined timestamp` errors from this compute method
> [MEX-662] fix undefined timestamp in case of no events

- src/modules/analytics/services/analytics.compute.service.ts
- src/modules/analytics/services/analytics.setter.service.ts
- src/services/elastic-search/entities/terms.query.ts
- src/services/elastic-search/services/es.events.service.ts
-  current implementation can suffer from infinite loop inside the compute token trading activity if the token only on other exchanges with the same event identifier
- added filtering by a set of pairs addresses for the ES query that retrieves the swap events for a token
```
query {
tradingActivity(
series: "MUNCHKIN-3865e6"
) {
timestamp
hash
action
inputToken {
tokenIdentifier
amount
}
outputToken {
tokenIdentifier
amount
}
}
}
```
- query should return an empty array
> [MEX-662]: Filter by pair address in ES query

- src/modules/analytics/models/trading.activity.model.ts
- src/modules/analytics/services/analytics.compute.service.ts
- src/services/crons/analytics.cache.warmer.service.ts
- There was a need of multiple Esdt Token attributes on frontend, and we were sending only the token identifier
- Action on TokenTradingActivity was not working properly, ( the quote / base computation was implemented only for pairTradingActivity )
- Change the model and the compute functions to return EsdtType for inputToken and OutputToken
- Implement quote / base computation for token Trading Activity
```
tradingActivity(series: "erd1qqqqqqqqqqqqqpgq5jnjpsukhl295ry3wjrd3gtff0amrgux2jpsz3reum") {
hash,
timestamp,
action,
inputToken {
identifier,
decimals,
balance
},
outputToken {
identifier,
decimals,
balance
}
}
```
> [ MEX-662 ] Changed input and output token type to Esdt and fix action on TokenTradingActivity 

- src/modules/analytics/services/analytics.compute.service.ts
- Trading Action ( SELL / BUY ) for Token Trading Activity was incorrect
- For Token Trading Activity, the tokenID provided will always be the quote token
```
tradingActivity(series: "WEGLD-bd4d79") {
hash,
timestamp,
action,
inputToken {
identifier,
balance,
decimals
},
outputToken {
identifier,
balance,
decimals
}
}
```
> [Mex-662] - Trading activity for tokens and pairs

- src/modules/currency-converter/services/currency.converter.service.ts
- For Cryptocurrencies The Price was returned instead of the rate
- Return The Rate for all Cryptocurrencies
```
currencyRates (symbols: ["EGLD", "WBTC", "WETH"]) {
symbol
rate
category
name
}
```
> [MEX-666] - Fix: Return Rates instead of prices for Crypto

- src/modules/fees-collector/services/fees-collector.compute.service.ts
- src/services/cache.warmer.module.ts
- src/services/crons/fees.collector.cache.warmer.service.ts
- src/services/crons/week.timekeeping.cache.warmer.service.ts
- src/services/crons/weekly.rewards.cache.warmer.service.ts
- src/submodules/week-timekeeping/services/week-timekeeping.setter.service.ts
- src/submodules/week-timekeeping/week-timekeeping.module.ts
- src/submodules/weekly-rewards-splitting/services/weekly-rewards-splitting.compute.service.ts
- week timekeeping data for farms, fees collector and staking contracts is used in various computations for user queries. The current implementation fetches this data on user request only, causing poor performance
- added 2 new cache warmers for week timekeeping and weekly rewards splitting data (for farms, staking and fees collector)
- small fix for certain fields returning "NaN" (division by 0)
- N/A
> [MEX-691] Weekly rewards and timekeeping cache warmers

- src/config/default.json
- increased gas limit for position creator single tokens transactions
- N/A
> [MEX-692] update gas limits for position creator

- src/config/default.json
- src/modules/auto-router/services/graph.service.ts
- due to the increasing number of pairs, computing all possible swap paths results in an array containing over 25k entries, which leads to performance degradation when iterating over it
- introduce a max depth limitation when computing possible paths
- N/A
> [MEX-719] Limit depth when computing all possible swap routes

- src/modules/auto-router/services/auto-router.service.ts
- src/modules/pair/mocks/pair.abi.service.mock.ts
- src/modules/pair/services/pair.abi.loader.ts
- src/modules/pair/services/pair.abi.service.ts
- the `getAllActivePairs` method used in the `swap` query performs multiple single GET requests from cache for fetching pairs state, reserves, fee percentage and token metadata
- use bulk get methods in `getAllActivePairs`
- fetch token metadata for unique token IDs 
- N/A
> [MEX-715] Swap query cache optimization

- src/helpers/proxy.network.provider.profiler.ts
- src/utils/metrics.collector.ts
- profiling without awaiting the result returns misleading durations for VM queries duration
- the function name is ignored and a generic metric is collected for all VM queries
- add missing await when querying a smart contract
- add a separate histogram for vm queries duration
- N/A
> [MEX-726] Fix VM query metrics

- src/services/crons/week.timekeeping.cache.warmer.service.ts
- src/services/crons/weekly.rewards.cache.warmer.service.ts
- src/submodules/weekly-rewards-splitting/services/weekly-rewards-splitting.compute.service.ts
- src/submodules/weekly-rewards-splitting/services/weekly.rewarrds.splitting.setter.service.ts
- src/submodules/weekly-rewards-splitting/specs/weekly-rewards-splitting.compute.service.spec.ts
- the current implementation performs multiple single requests to redis when computing user rewards apr field
- use batch get methods for token prices and metadata in weekly rewards compute methods
- cache warm rewards weekApr + invalidate smaller arrays in loop
- refactor week timekeeping cache warmer: cache warm start + end epochs for all claim weeks
- N/A
> [MEX-725] Optimize weekly rewards computations

- src/modules/analytics/analytics.module.ts
- src/modules/analytics/analytics.resolver.ts
- src/modules/analytics/models/query.args.ts
- src/modules/analytics/services/analytics.pair.service.ts
- src/modules/analytics/services/analytics.pair.setter.service.ts
- src/modules/analytics/validators/price.candles.args.validator.ts
- src/services/analytics/interfaces/analytics.query.interface.ts
- src/services/analytics/mocks/analytics.query.service.mock.ts
- src/services/analytics/services/analytics.query.service.ts
- src/services/analytics/timescaledb/timescaledb.query.service.ts
- src/services/crons/analytics.cache.warmer.service.ts
- src/utils/analytics.utils.ts
- priceCandles query didn't have any caching
- Implement caching for the priceCandles query
```
query {
priceCandles (series: "HTM-f51d55", metric: "priceUSD", start: "1740644706", end:"1741249506", resolution: HOUR_4) {
time,
ohlc
}
}
```
> [MEX-722] Implement caching for the pairCandles query

- src/modules/position-creator/services/position.creator.transaction.ts
- src/modules/position-creator/specs/position.creator.transaction.spec.ts
- not enough gas set on position creator single tokens transactions
- fixed compute gas limit for single tokens transactions with multiple swaps
- N/A
> [MEX-737] position creator gas fix

- src/modules/farm/base-module/services/farm.abi.service.ts
- src/modules/farm/base-module/services/farm.setter.service.ts
- src/modules/pair/services/pair.setter.service.ts
- src/modules/staking-proxy/services/staking.proxy.setter.service.ts
- src/modules/staking/services/staking.setter.service.ts
- src/modules/tokens/services/token.setter.service.ts
- src/services/crons/farm.cache.warmer.service.ts
- src/services/crons/pair.cache.warmer.service.ts
- src/services/crons/staking.cache.warmer.service.ts
- src/services/crons/staking.proxy.cache.warmer.service.ts
- src/services/crons/tokens.cache.warmer.service.ts
- src/services/crons/week.timekeeping.cache.warmer.service.ts
- src/services/generics/generic.setter.service.ts
- src/submodules/week-timekeeping/services/week-timekeeping.setter.service.ts
- currently, the in-memory cache is being invalidated too frequently due to deleteCacheKeys events received via pubsub. These events, primarily triggered by the cache warmer instance, reduce the overall benefit of caching by causing unnecessary cache refreshes
- add `setDataOrUpdateTtl` to the `GenericSetterService`. This method is designed to update cache entries without returning a cache key (unlike the existing setData method)
- utilize `setDataOrUpdateTtl` for updating specific fields that do not require frequent invalidation. This approach aims to maintain the integrity of in-memory caching while reducing unnecessary refresh events. 
- N/A
> [MEX-734] Cache invalidation improvements

- src/modules/analytics/analytics.module.ts
- src/modules/analytics/analytics.resolver.ts
- src/modules/analytics/global.rewards.resolver.ts
- src/modules/analytics/models/global.rewards.model.ts
- src/modules/analytics/models/query.args.ts
- src/modules/analytics/services/analytics.setter.service.ts
- src/modules/analytics/services/global.rewards.service.ts
- src/modules/farm/base-module/services/farm.abi.service.ts
- src/services/crons/analytics.cache.warmer.service.ts
- Front end needs data regarding rewards distribution for the past 4 weeks from feesCollector, farms and staking farms
- Implemented a new query
```
query {
globalRewards (weekOffset: 1) {
feesCollectorGlobalRewards {
__typename
totalRewardsUSD,
energyRewardsUSD
},
farmsGlobalRewards {
__typename
pairAddress
firstToken {
identifier, 
name,
price
},
secondToken {
identifier, 
name,
price
},
totalRewardsUSD,
energyRewardsUSD
}
stakingGlobalRewards {
__typename
farmingToken {
identifier, 
name,
price
},
totalRewardsUSD,
energyRewardsUSD
}
}
}
```
> MEX-730 New Global Rewards query

- src/modules/locked-token-wrapper/services/locked-token-wrapper.transaction.service.ts
- src/modules/locked-token-wrapper/specs/locked.token.wrapper.transaction.service.spec.ts
- WXMEX SC doesn't check for unlocking epoch anymore
- removed check for wrapped locked token unlock epoch for underlying token
```
query UnwrapLockedToken {
unwrapLockedToken(
inputTokens: { tokenID: "WXMEX-0b76a1", nonce: 1, amount: "1" }
) {
data
gasLimit
}
}
```
- query should return transaction even though the xMEX wrapped in unlockable
> [MEX-769] wxmex unlock transaction fix

- src/modules/aggregators/services/coin.gecko.service.ts
- base and target currency should be inverted
- add a method for determining base and target tokens
- pairs returned on GET request to `/coingecko/tickers` should always have the common token as `targetCurrency`
> [MEX-771] Fix token order for Coingecko endpoint

- src/modules/smart-router-evaluation/dtos/swaps.evaluation.params.ts
- src/modules/smart-router-evaluation/services/smart.router.evaluation.service.ts
- src/modules/smart-router-evaluation/smart.router.evaluation.controller.ts
- src/modules/smart-router-evaluation/smart.router.evaluation.module.ts
- src/private.app.module.ts
- we need a way to extract information stored in the mongoDB
- add private app controller that exposes endpoints needed to populate dashboard
- add service methods for querying mongodb (with pagination, filtering and sorting)
- GET request to `<PRIVATE_API_URL>/smart-router/swaps?offset=0&size=10&deltaComparison=gt&delta=-1` should return an array of comparisson documents like this : 
```
[
...
{
_id: "680f95e6f3984c2210170bef",
sender: "erd1rwsq0fxjrce9955hvvl3qrpl96xmuuxch9m6wlhxx6zs0n2v3hvqyu4lm5",
txHash: "fbcc8df11c595fdd1b3979f85c3b1c1416e92ce070625dae22d7d3db50669a67",
txData: "Y29tcG9zZVRhc2tzQDAwMDAwMDBiNTU1MzQ0NDMyZDMzMzUzMDYzMzQ2NTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwNDAyMWRhZGIwQEBAMDJAMDAwMDAwMTQ3Mzc3NjE3MDU0NmY2YjY1NmU3MzQ2Njk3ODY1NjQ0OTZlNzA3NTc0MDAwMDAwMGI1NTUzNDQ0MzJkMzMzNTMwNjMz …
```
> [MEX-766] Smart Router evaluation REST endpoints

- src/config/default.json
- src/modules/auto-router/services/smart.router.service.ts
- the smart router algorithm can currently recommend up to 15 separate routes. This is not feasible due to gas cost
- introduce a loop that prunes the route getting the smallest share of input (it adds the least to total output - its marginal return is lowest by construction of the Lagrange solution) and recomputes optimal phi after every removal
- the loop runs as long as the number of suggested routes > config `MAX_SMART_SWAP_ROUTES`
- persisted smart swaps should have at most 4 routes
> [MEX-776] Limit max routes for smart swaps

- src/modules/smart-router-evaluation/services/smart.router.evaluation.cron.ts
- src/modules/smart-router-evaluation/services/smart.router.evaluation.service.ts
- the evaluation cron groups swap documents by performing a MD5 hash of the proposed transaction (sender, tx data, token in/out, auto router data, smart router data and output delta). 
Because the smart router output could be different for multiple swap documents representing the same tx, the resulting MD5 hash is different, and the cronjob interprets it as a separate transaction.  This results in multiple documents having the same txHash, skewing the result set.
- check if a document with a txHash exists before performing an insert 
- N/A
> [MEX-774] Fix evaluation cron handling of multiple smart router swaps with same txHash

- src/modules/farm/specs/farm.v2.compute.service.spec.ts
- src/modules/farm/v2/services/farm.v2.abi.service.ts
- src/modules/farm/v2/services/farm.v2.compute.service.ts
- src/modules/staking/services/staking.abi.service.ts
- src/modules/staking/services/staking.compute.service.ts
- xExchange v3.3 protocol release removed the view function: `getUndistributedBoostedRewards`
- updated storage name for last claim undistributed boosted rewards week
- updated compute for claimable undistributed boosted rewards
```
query Farms {
farms {
... on FarmModelV2 {
address
farmToken {
collection
}
undistributedBoostedRewards
}
}
}
```
- query should return value if there were no claims between `last_claim_week` and `current week - (USER_MAX_CLAIM_WEEKS + 1)`
> [MEX-779] fix undistributed boosted rewards

- src/modules/smart-router-evaluation/services/smart.router.evaluation.cron.ts
- src/modules/smart-router-evaluation/smart.router.evaluation.cron.module.ts
- src/modules/smart-router-evaluation/smart.router.evaluation.module.ts
- race condition in evaluation cron caused unpredictable behaviour when pruning swap mongodb documents 
- use `@LockAndRetry` decorator 
- simplify cron by only issuing update operations (delete is handled when timestamp is > 10 minutes)
- add verbose logging
- N/A
> [MEX-774] Apply lock-and-retry decorator to evaluation cron

- src/services/analytics/services/analytics.query.service.ts
- src/services/analytics/timescaledb/timescaledb.query.service.ts
- src/services/crons/aws.query.cache.warmer.service.ts
- the query `values24h(series: "factory", metric: "totalLockedValueUSD")` sporadically returns the wrong amount for the current hour. The bug occurs whenever the analytics cache warmer cron runs over an hour boundary (eg. starts at 08:50 and runs until 09:01). The Set with unique timestamps across all pairs will contain an extra value - for hour 09:00. Since not all pairs have values for this timestamp (the runs before 09:00), the last value in the array will be smaller.
- add `time` parameter to 'getValues24h' method in `TimescaleDBQueryService`
- use same timestamp for all queries performed by the analytics cache warmer
- The query should return the correct values even if the cron job runs past an hour boundary
```
query chartLatestCompleteValues {
values24h(series: "factory", metric: …
```
> [MEX-791] Fix factory series TVL

- src/modules/push-notifications/crons/push.notifications.energy.ts
- This Cron is not tested properly, will be activated in the future
- Deactivate temporarily the cron
- N/A
> MEX-748 Deactivate Negative Energy Notifications

- src/helpers/api.config.service.ts
- `ACCOUNTS_ELASTIC_SERVICE` can be undefined depending on the environment
- added a fallback to default elastic search URL
- API instances should not throw an error from ApiConfigService if env value is missing
> [MEX-748] add fallback for ACCOUNTS_ELASTIC_SERVICE config

- src/modules/farm/base-module/services/farm.setter.service.ts
- src/services/crons/farm.cache.warmer.service.ts
- slow response time on farms query requesting the `undistributedBoostedRewards` field. The underlying compute method can trigger up to 100 VM query calls (function `getRemainingBoostedRewardsToDistribute`) for each farm, resulting in ~2000 VM query calls on a cache miss
- add a cron job that refreshes the cache value for `undistributedBoostedRewards` of each v2 farm
- N/A
> [MEX-826] Farms undistributed boosted rewards cache warmer

- src/modules/trading-contest/services/trading.contest.cron.ts
- src/modules/trading-contest/services/trading.contest.service.ts
- src/modules/trading-contest/trading.contest.cron.module.ts
- src/modules/trading-contest/trading.contest.module.ts
- src/services/cache.warmer.module.ts
- src/services/elastic-search/services/es.operations.service.ts
- swap events (received through RabbitMQ) originating from transactions on the Composable Tasks or Router SCs don't expose the original sender. That information is found in Elastic Search operations index with a small delay
- add cron for resolving contest participants (sender) from ES
- N/A
> [MEX-824] Trading Contest participant resolver cron

- package-lock.json
- package.json
- src/modules/trading-contest/controllers/trading.contest.admin.controller.ts
- src/modules/trading-contest/controllers/trading.contest.controller.ts
- src/modules/trading-contest/dtos/contest.leaderboard.dto.ts
- src/modules/trading-contest/dtos/create.contest.dto.ts
- src/modules/trading-contest/pipelines/global.leaderboard.pipeline.ts
- src/modules/trading-contest/pipelines/participant.stats.pipeline.ts
- src/modules/trading-contest/pipelines/participant.token.stats.pipeline.ts
- src/modules/trading-contest/schemas/trading.contest.schema.ts
- src/modules/trading-contest/services/trading.contest.service.ts
- src/modules/trading-contest/trading.contest.module.ts
- src/modules/trading-contest/types.ts
- src/private.app.module.ts
- src/public.app.module.ts
- expose endpoints for creating contests, viewing contest leaderboards, and specific address ranking
- add admin controller and expose `/trading-contests` route in private app
- add aggregation pipelines for leader board and specific address rank
Exposed in private API : 
- `GET /trading-contests` - returns all trading contests
- `POST /trading-contests` - with the following body to create a new contest : 
```
{
"name": "Stable Competition",
"minSwapAmountUSD": 5,
"start": 1750076131,
"end": 1751276548,
"tokensPair": ["USDC-350c4e", "MEX-a659d0"],
"tokens": [],
"pairAddresses": []
"requiresRegistration": false,
}
```
The endpoint accepts a `tokens` array, a `pairAddresses` array (to create contests focused on specific pairs), and a `tokensPair` array of exactly 2 items (to create …
> [MEX-825] Trading Contest REST API

- src/modules/trading-contest/pipelines/participant.token.stats.pipeline.ts
- src/modules/trading-contest/services/trading.contest.service.ts
- src/modules/trading-contest/types.ts
- information about the total swapped token amounts is needed, besides the computed USD value
- update participant token stats aggregation pipeline
- update types
- Response from `POST /trading-contests/<CONTEST_UUID>/participants/<ADDRESS>/token-stats` should look like this : 
```
[
{
"tokenID": "SPK-81618e",
"buyVolumeUSD": 50.68056195024269,
"buyAmount": "90652.446423604457233126",
"sellVolumeUSD": 103.89205086538817,
"sellAmount": "183849.097107306660264211",
"buyCount": 2,
"sellCount": 4
},
{
"tokenID": "WEGLD-a28c59",
"buyVolumeUSD": 103.89205086538817,
"buyAmount": "6.904570039319697463",
"sellVolumeUSD": 50.68056195024269,
"sellAmount": "3.369568234352152333",
"buyCount": 4,
"sellCount": 2
}
]
```
> [MEX-845] Add token amounts to trading contest participant response

- src/modules/auto-router/models/auto-route.model.ts
- src/modules/auto-router/services/auto-router.service.ts
- src/modules/auto-router/specs/smart.router.service.spec.ts
- the fee for smart swaps was not exposed on the model; it was only used to compute the amount encoded in the transaction arguments 
- add `feeAmount` and `feePercentage` fields to `SmartSwapModel`
- update the value of the `amountOut` field ( = the amount computed by the algorithm - the % fee)
- update unit tests
- `swap` query 
```
query SmartSwapQueryWithFee {
swap(
amountIn: "900000000"
tokenInID: "USDC-350c4e"
tokenOutID: "EMR-6310dc"
) {
smartSwap {
amountOut
feeAmount
feePercentage
routes {
tokenRoute
pricesImpact
intermediaryAmounts
pairs {
address
}
}
}
}
}
```
> [MEX-849] Expose fee in smart swap model

- src/modules/pair/services/pair.transactions.service.ts
- BTC based pools creation would hit the limitation because of the BTC price
- increase the maximum requirement for permanently liquidity locked in a pool
- N/A
> [MEX-855] increase minimum permanent liquidity locked

- src/modules/auto-router/services/auto-router.service.ts
- src/modules/auto-router/specs/auto-router.service.spec.ts
- src/modules/auto-router/specs/smart.router.service.spec.ts
- src/modules/pair/mocks/pair.constants.ts
- the `tokensPriceDeviationPercent` field on swap models is currently only populated when the value exceedes the config value for `MAX_SWAP_SPREAD`
- always return the value from the compute methods
- throw an error when a smart swap transaction is requested, and the spread is too large
- update unit tests : add tests that check for presence of error when spread is too large; update missing field where needed
- N/A
> [MEX-857] Populate 'tokensPriceDeviationPercent' field on swap model

- src/helpers/decorators/caching.decorator.ts
- src/services/generics/generic.setter.service.ts
- the TTL for the in-memory caching of `undefined` / `null` is currently incorrect, when a value is present in the remote cache, and the local cache is updated with that value.  
- the current implementation of the `setDataOrUpdateTtl` in the `GenericSetterService`  can lead to stale / out-of-sync data in the in-memory cache on the cache warmer instance
- update `GetOrSetCache` decorator: set correct TTL when updating local cache from remote cached value
- update `setDataOrUpdateTtl` method in generic setter: add extra check -> compare remote cached value with in-memory cached value when deciding if a TTL update is sufficient
- N/A
> [MEX-784] Fix local cache TTL for undefined values

- src/modules/trading-contest/controllers/trading.contest.controller.ts
- src/modules/trading-contest/dtos/contest.leaderboard.dto.ts
- src/modules/trading-contest/pipelines/contest.stats.pipeline.ts
- src/modules/trading-contest/pipelines/global.leaderboard.pipeline.ts
- src/modules/trading-contest/pipelines/participant.stats.pipeline.ts
- src/modules/trading-contest/pipelines/token.stats.pipeline.ts
- src/modules/trading-contest/services/trading.contest.service.ts
- src/modules/trading-contest/types.ts
- no way to have an insight into the general performance of a specific contest (without fetching the entire leaderboard)
- no straight forward way to paginate the leaderboard, without knowing the total participant count in advance
- mongodb aggregation pipeline for contest stats; returns stats in 3 flavors using $facet: summary, bySwapType, daily
- refactor participant token stats agg. pipeline into a more generic pipeline allowing optional filtering by participant
- update leaderboard pipeline to include total participant count (to help with pagination); rely on $facet for improved performance at db level
- update types and dtos to match the new and updated pipelines
- refactor trading contest service to properly make use of the new and updated aggregation pipelines
- add …
> [MEX-863] Trading Contest stats endpoints

- src/modules/push-notifications/models/custom.push.notification.payload.ts
- src/modules/push-notifications/push.notifications.controller.ts
- src/modules/push-notifications/services/push.notifications.energy.service.ts
- allow custom push notifications to be sent besides
- add method for sending a custom notification to all users with energy
- expose endpoint (private API) that allows sending custom notifications to specific addresses / all users with energy
`POST <PRIVATE_API>/push-notifications/send-custom`
- request body for notification to specific addresses (max 100)
```
{
"notificationKey": "customAnnouncement",
"addresses": ["erd19xm2msh5sfvs5je9axp3jhzm2r5dpez8qfh88wxvcv97z24msqwqm2xn56"],
"content": {
"title": "xExchange: Custom Announcement",
"body": "This is the body of the notification",
"route": "/portfolio",
"iconUrl": "https://xexchange.com/assets/imgs/mx-logos/xexchange-logo@2x.webp"
}
}
```
- request body for notification to all users with energy in a specific past epoch
```
{ …
```
> [MEX-888] Endpoint for custom push notifications
