package-lock.json, src/modules/analytics/services/analytics.compute.service.ts, src/submodules/weekly-rewards-splitting/services/weekly-rewards-splitting.abi.service.ts
=> Merge main into feat/analytics-v2

package-lock.json, src/services/multiversx-communication/mx.proxy.service.ts
Signed-off-by: Claudiu Lataretu <claudiu.lataretu@gmail.com>
- race condition on instantiate farm singleton smart contract object
- use a more specialized key for smart contract objects stored in singleton map
- cold start service, query farm v2 with `time` and `boostedYieldsRewardsPercenatage` fields
=> [SERVICES-1234] use a specialized key for smart contract singleton

package-lock.json, src/modules/staking/models/staking.model.ts, src/modules/staking/services/staking.compute.service.ts, src/modules/staking/services/staking.getter.service.ts, src/modules/staking/services/staking.setter.service.ts, src/modules/staking/specs/staking.compute.service.spec.ts, src/modules/staking/staking.module.ts, src/modules/staking/staking.resolver.ts, src/services/crons/staking.cache.warmer.service.ts
Signed-off-by: Claudiu Lataretu <claudiu.lataretu@gmail.com>
- compute real APR for staking farms contracts
- added new method for computing APR based rewards distribution model.
- query stakingFarms with `apr` field
=> [SERVICES-1232] add compute for staking farms real APR value

src/modules/farm/v2/services/farm.v2.compute.service.ts
Signed-off-by: Claudiu Lataretu <claudiu.lataretu@gmail.com>
- farms `baseAPR` contains both farm base reward APR and pair `feesAPR`
- remove pair `feesAPR` from farm `baseAPR`
- query farms V2 with fields `baseAPR` and `pair -> feesAPR`. Adding the values should lead to same result as before
=> [SERVICES-1294] remove pair feesAPR from farmV2 baseAPR

package-lock.json
=> Merge development into feat/analytics-v2

src/modules/rabbitmq/handlers/weeklyRewardsSplitting.handler.service.ts, src/modules/user/services/userEnergy/user.energy.getter.service.ts, src/modules/user/services/userEnergy/user.energy.setter.service.ts, src/services/generics/generic.setter.service.ts
=> Merge main into development

src/helpers/api.config.service.ts, src/modules/analytics/specs/analytics.service.spec.ts, src/modules/farm/specs/farm.compute.service.spec.ts, src/modules/farm/specs/farm.service.spec.ts, src/modules/farm/specs/farm.transactions.service.spec.ts, src/modules/farm/specs/farm.v1.2.compute.service.spec.ts, src/modules/farm/specs/farm.v1.3.compute.service.spec.ts, src/modules/pair/pair.module.ts, src/modules/pair/services/pair.compute.service.ts, src/modules/pair/specs/pair.compute.service.spec.ts, src/modules/tokens/services/token.compute.service.ts, src/modules/tokens/token.module.ts, src/modules/tokens/token.resolver.ts, src/modules/user/specs/user.service.spec.ts, src/services/external-communication/api.cmc.getter.service.ts, src/services/external-communication/api.cmc.service.ts, src/services/external-communication/external.communication.module.ts, src/services/external-communication/mocks/api.cmc.getter.service.mock.ts, src/submodules/weekly-rewards-splitting/specs/weekly-rewards-splitting.compute.service.spec.ts
- USDC price in USD not correlated
- use external price fetcher to get USD price of USDC
- USDC tokens should display actual USD value
=> [SERVICES-1411] USDC price feed

src/services/analytics/data-api/entities/data.api.entities.ts
- use new timescaleDB entities
- changed timescaleDB entitites
- N/A
=> [SERVICES-1295] analytics migration

src/config/devnet.json, src/modules/remote-config/remote-config.getter.service.ts, src/services/analytics/data-api/data-api.query.service.ts, src/services/analytics/data-api/migration/1677412507858-xExchange.ts, src/services/analytics/data-api/migration/1678783387115-xExchange.ts
- new materialized view added
- add migration for new materialized view 
- N/A
=> [SERVICES-1295] Add new migrations

src/services/analytics/data-api/entities/data.api.entities.ts, src/services/analytics/data-api/migration/1678783387115-xExchange.ts, src/services/crons/aws.query.cache.warmer.service.ts, src/services/crons/pair.cache.warmer.service.ts
- migrations run fails
- analytics cron jobs runs too often
- fix materialized view create
- increase cron jobs schedule time
- `npm run typeorm:run-migrations -- --transaction each`
=> [SERVICES-1295] Token burned migration and analytics cron jobs

src/services/crons/pair.cache.warmer.service.ts, src/services/multiversx-communication/mx.api.service.ts, src/utils/token.type.compare.ts
- MVX API can response with bad tokens metadata
- add fallback mechanism to get tokens metadata from MVX gateway
- `tokens` query should respond with correct tokens decimals
=> [SERVICES-1454] fix tokens decimals

src/common.app.module.ts, src/helpers/decorators/error.logger.ts, src/main.ts, src/modules/distribution/services/abi-distribution.service.ts, src/modules/energy/energy.resolver.ts, src/modules/energy/services/energy.abi.service.ts, src/modules/energy/services/energy.setter.service.ts, src/modules/farm/base-module/services/farm.abi.service.ts, src/modules/farm/v2/services/farm.v2.abi.service.ts, src/modules/fees-collector/services/fees-collector.abi.service.ts, src/modules/locked-asset-factory/services/abi-locked-asset.service.ts, src/modules/locked-token-wrapper/services/locked-token-wrapper.abi.service.ts, src/modules/metabonding/services/metabonding.abi.service.ts, src/modules/pair/services/pair.abi.service.ts, src/modules/price-discovery/services/price.discovery.abi.service.ts, src/modules/proxy/services/proxy-abi.service.ts, src/modules/proxy/services/proxy-farm/proxy-farm-abi.service.ts, src/modules/proxy/services/proxy-pair/proxy-pair-abi.service.ts, src/modules/router/services/abi.router.service.ts, src/modules/simple-lock/services/simple.lock.abi.service.ts, src/modules/staking-proxy/services/staking.proxy.abi.service.ts, src/modules/staking/services/staking.abi.service.ts, src/modules/token-unstake/services/token.unstake.abi.service.ts, src/modules/wrapping/abi-wrap.service.ts, src/public.app.module.ts, src/services/caching/cache.service.ts, src/services/generics/generic.abi.service.ts, src/services/generics/generic.setter.service.ts, src/submodules/week-timekeeping/services/week-timekeeping.abi.service.ts, src/submodules/weekly-rewards-splitting/services/weekly-rewards-splitting.abi.service.ts
- normalize logging messages across the entire application
- use nest-winston module to replace the base Nest logging service
- add a error logger decorator to be used for logging
- remove unncesary logging messages
- console should display new winston-module formatted messages
=> [SERVICES-1480] error logger decorator

src/modules/distribution/specs/distribution.transactions.service.spec.ts
- keep consistency on project structure
- none
- N/A
=> [SERVICES-1513] distribution module specs

src/config/mainnet.json
- mainnet escrow contract deployment
- add mainnet escrow contract address
- N/A
=> [SERVICES-1310] add mainnet escrow contract address

src/config/staging.json
- add escrow address to staging config
- none
- N/A
=> [SERVICES-1310] add escrow address to staging config

src/submodules/weekly-rewards-splitting/weekly-rewards-splitting.resolver.ts
- keep consistency across resolvers
- removed generic resolver dependency from weekly rewards splitting resolver
- N/A
=> [SERVICES-1542] Weekly rewards splitting no generic resolver

src/modules/rabbitmq/rabbitmq.module.ts
- events notifier app does not start
- add missing import
- events notifier app should start properly
=> [SERVICES-1553] add missing import on rabbitmq module

src/modules/farm/v2/services/farm.v2.transaction.service.ts
- missing constructor on FarmTransactionServiceV2
- add constructor for farm V2 transaction service
- N/A
=> [SERVICES-1520] add constructor for farm V2 transaction service

src/config/testnet.json
- New testnet setup
- updated testnet config with new sc addresses
- N/A
=> [SERVICES-1601] new testnet setup config

src/config/testnet.json
- changed USDC testnet token
- updated pair and farm for usdc
- N/A
=> [SERVICES-1601] update testnet config

src/config/mainnet.json
- deployed new farms on mainnet
- added new farms addresses for mainnet config
- N/A
=> New mainnet farms: ZPAY & BHAT

src/config/staging.json
- deployed new farms on mainnet
- added new farms addresses for mainnet config
- N/A
=> Added new farms on staging config

src/config/default.json, src/modules/token-unstake/specs/token.unstake.transaction.service.spec.ts
=> increase cancelUnbond gasLimit

src/config/default.json
=> Merge main into feat/code-refactor-with-decorators

src/modules/rabbitmq/handlers/router.handler.service.ts, src/utils/token.type.compare.ts
=> Merge development into feat/code-refactor-with-decorators

src/config/devnet.json, src/config/mainnet.json, src/config/staging.json, src/config/testnet.json
- missing configs for swap enable
- add configs for all environments
- N/A
=> [SERVICES-1670] add missing constants configs

src/config/mainnet.json, src/config/staging.json
- wrong token IDs
- use correct token IDs for mainnet
- N/A
=> [SERVICES-1670] use correct tokens for swap constants

src/config/staging.json
- simple lock address on staging config missing
- add simple lock address on staging config
- N/A
=> Simple lock address on staging config

src/config/default.json
- update gas limit
- multiPairSwapMultiplier update
- N/A
=> Update multi pair swap gas limit multiplier

src/modules/governance/governance.contract.resolver.ts, src/modules/governance/models/energy.contract.model.ts, src/modules/governance/services/governance.service.ts
- resolve feeToken as an EsdtToken that includes also assets of the token
=> MEX-323: resolve feeToken as EsdtToken

src/modules/governance/models/proposal.votes.model.ts, src/modules/governance/services/governance.abi.service.ts
-  Add total votes & percentages fields for proposal votes
=> MEX-324: proposal total votes and percentages

src/config/default.json, src/modules/governance/governance.module.ts, src/modules/governance/governance.transaction.resolver.ts, src/modules/governance/models/governance.proposal.model.ts, src/modules/governance/services/governance.abi.service.ts
-  Add transaction resolver for governance module
=> MEX-325: governance transaction resolver

src/config/devnet.json, src/modules/governance/governance.energy.contract.resolver.ts, src/modules/governance/models/governance.proposal.model.ts, src/modules/governance/services/governance.service.ts
=> MEX-329: fix and add filters

src/config/mainnet.json, src/config/staging.json
- new farm deploy for hatom
- add farm address for mainnet and staging
- N/A
=> Add hatom farm address on mainnet

src/config/devnet.json
- update governance contract address
=> update governance contract

src/modules/governance/models/governance.proposal.model.ts, src/modules/governance/models/governance.union.ts, src/modules/governance/services/governance.description.service.ts
- fix cammelCase issue for Description
- remove hash field
=> MEX-348: governance description fixes

src/modules/governance/services/governance.compute.service.ts, src/services/multiversx-communication/mx.api.service.ts
- Fix extract proposalId from tx payload
=> MEX-349: Fix extract proposalId from tx payload

src/modules/governance/resolvers/governance.proposal.resolver.ts
- wrong display on frontend
- remove sqrt from user voting power resolver
- N/A
=> [MEX-350] remove sqrt from user voting power

src/modules/governance/services/governance.token.snapshot.merkle.service.ts
=> MEX-352: fix roothash check

.github/workflows/unit.tests.yml, Dockerfile, README.md
- old version for node used
- use LTS version of node: 18.x
- N/A
=> [SERVICES-1786] update node version to 18.x

src/modules/rabbitmq/handlers/governance.handler.service.ts
- fix updating userVoteTypesForContract in handleGovernanceVoteEvent method
=> MEX-356: fix userVoteTypesForContract 

src/config/default.json, src/config/devnet.json, src/config/index.ts, src/config/mainnet.json, src/config/staging.json, src/config/testnet.json, src/modules/governance/services/governance.service.ts, src/utils/governance.ts
- The smoothing function is not determined by the type of the governance SC, thus we need a way to differentiate between different kinds of SCs
=> MEX-363: add configurable smoothingFunction for each governance SC

src/config/devnet.json
- devnet config typo
- remove typo
- app should start on devnet
=> [MEX-363] fix devnet config

src/services/multiversx-communication/mx.communication.module.ts
- missing import of cache module
- add cache module import in mx communication
- N/A
=> [SERVICES-1834] fix missing imports in mx.communication module

src/modules/governance/governance.module.ts, src/modules/governance/services/governance.setter.service.ts, src/services/cache.warmer.module.ts, src/services/crons/governance.cache.warmer.service.ts
- Status updates or new proposals will automatically be reflected
=> MEX-366: cronjob for updating proposals and their statuses

src/config/devnet2.json
- new devnet deployment
- add new config for devnet2
- N/A
=> [SERVICES-1842] Add devnet2 config

src/config/devnet2.json
- updated new devnet2 configs
- updated new devnet2 configs
- N/A
=> [SERVICES-1842] more devnet 2 configs

src/config/devnet2.json
=> Merge development into feat/nestjs-sdk-integration

src/config/devnet2.json
- new proxy dex v1 deploy
- updated proxy dex v1 address
- N/A
=> [SERVICES-1842] update proxy dex v1 address

src/config/staging.json
- deployed new farms
- added new farms to staging config
- N/A
=> [SERVICES-1855] add new farms on staging config

src/config/mainnet.json
- new farms on mainnet
- added farms addresses on mainnet config
- N/A
=> [SERVICES-1855] add new farms on mainnet config

src/modules/energy/energy.module.ts, src/modules/energy/energy.update.resolver.ts, src/modules/energy/models/energy.update.model.ts
- missing resolver for energy update contract
- added new model for energy update contract
- added resolver for energy update model
```
query EnergyUpdate {
energyUpdate {
address
}
}
```
=> [SERVICES-1872] energy update resolver

src/modules/farm/mocks/farm.v2.abi.service.mock.ts, src/modules/farm/specs/farm.v2.compute.service.spec.ts, src/modules/farm/v2/farm.v2.resolver.ts, src/modules/farm/v2/services/farm.v2.abi.service.ts, src/modules/farm/v2/services/farm.v2.compute.service.ts, src/modules/farm/v2/services/farm.v2.service.ts, src/modules/farm/v2/services/interfaces.ts, src/modules/user/user.info-by-week.resolver.ts, src/services/context/mocks/context.getter.service.mock.ts, src/services/crons/cache.warmer.service.ts, src/services/multiversx-communication/mx.api.service.ts
- use user total farm position to compute weekly rewards
- remove liquidity arguments from methods used to compute user weekly rewards
=> [MEX-375] update compute rewards

src/config/default.json, src/modules/router/specs/router.transactions.service.spec.ts
- not enough gas error
- update gas limit
- N/A
=> Update gas limit for set swap enable transaction

src/config/testnet.json
- deployed new contracts for escrow and token unstake
- updated testnet addresses
- N/A
=> Updated testnet addresses config

src/config/testnet.json
- invalid addresses for energy update and token unstake contracts
- updated addresses for energy update and token unstake contracts
- N/A
=> Update testnet config addresses

src/modules/escrow/escrow.resolver.ts, src/modules/escrow/mocks/escrow.abi.service.mock.ts, src/modules/escrow/services/escrow.abi.service.ts, src/modules/escrow/services/escrow.transaction.service.ts, src/modules/escrow/services/interfaces.ts, src/modules/escrow/specs/escrow.transaction.service.spec.ts, src/modules/locked-token-wrapper/locked-token-wrapper.module.ts, src/modules/locked-token-wrapper/services/locked-token-wrapper.transaction.service.ts, src/modules/locked-token-wrapper/specs/locked.token.wrapper.transaction.service.spec.ts, src/services/multiversx-communication/mx.api.service.mock.ts
- check for unlockable locked tokens from escrow & wrapped locked token contracts
- update withdraw escrow to check if received unlockable locked tokens
- updated unwrapLockedToken to check if received unlockable locked tokens
=> [SERVICES-2035] escrow & wrapped locked token unlockable check

src/config/default.json
- swap transactions fails with not enough gas
- update gas limit for swap transactions
- N/A
=> [SERVICES-1974] swap gas limits

src/config/default.json
- Not enough gas
- update gas limit
- N/A
=> [SERVICES-1974] Update gas limit for enter farm

src/config/testnet.json
- deploy testnet contracts
- added address for testnet contracts
- N/A
=> [testnet] new testnet addresses

src/config/default.json, src/modules/tokens/token.resolver.ts
=> Merge development into feat/xexchange-v3

src/config/default.json, src/modules/staking/specs/staking.transactions.service.spec.ts
- failed transactions with not enough gas
- updated gas limits for some transactions
- N/A
=> [testnet] update gas limits

src/config/default.json
- new mainnet upgrade to 1.6.0
- update gas limits configs
- N/A
=> config: update gas limits for mainnet

src/config/default.json, src/modules/router/specs/router.transactions.service.spec.ts
- update gas limits
- update gas limits on default config
- N/A
=> Update gas limits for mainnet

src/config/default.json
- updated gas limits for transactions
- N/A
=> [config] update gas limits for simple lock contract

src/config/default.json, src/modules/user/services/userEnergy/user.energy.compute.service.ts
=> [SERVICES-2105] revert user active farms

src/config/mainnet.json, src/config/staging.json
- deployed TADA farm
- deployed TADA farm
- N/A
=> Add TADA farm

src/modules/user/services/userEnergy/user.energy.compute.service.ts
- caching on user active farms V2 disabled
- reenable caching on user active farms V2
- N/A
=> [SERVICES-2105] reenable caching on user active farms V2

src/config/default.json
- update gas limits
- update gas limits from default config
- N/A
=> [config] Update gas limit for proxy exit farm v1.2

package-lock.json, package.json, src/modules/auth/native.auth.guard.ts
- fix impersonate on native auth server
- upgraded native-auth-server package to 1.0.15
- added custom impersonate callback
- N/A
=> [SERVICES-2112] upgrade native auth server

src/config/default.json, src/modules/position-creator/specs/position.creator.transaction.spec.ts
- insufficient gas error
- updated gas limit for stake single token
- N/A
=> [MEX-410] update gas limit for position creator

src/config/default.json
- update gas limits for v1.2 farms
- N/A
=> [config] update gas limits for v1.2 farms

src/modules/auth/native.auth.guard.ts
- revert to previous way to impersonate address
- added impersonate address from request headers
- N/A
=> [SERVICES-2112] use impersonate-address from request headers

src/modules/proxy/proxy.transaction.resolver.ts
- wrong transaction generator called for increase wrapped farm token energy
- use increase proxy farm token energy method
- N/A
=> [MEX-397] fix xmexfarm energy increase

src/config/default.json, src/modules/position-creator/services/position.creator.transaction.ts, src/modules/position-creator/specs/position.creator.transaction.spec.ts
- unable to fine tune the gas limits for various position creator transactions
- added granular configs fro position creator gas limits
- N/A
=> [MEX-443] position creator gas limits

src/config/default.json
- not enough gas error
- update gas limit for energy position 
- N/A
=> [MEX-443] update gas limit for energy position

src/config/default.json, src/modules/auto-router/specs/auto-router.service.spec.ts, src/modules/composable-tasks/specs/composable.tasks.transaction.spec.ts, src/modules/pair/specs/pair.transactions.service.spec.ts
- update config for compose tasks gas limit
- N/A
=> [MEX-443] update gas limits for compose tasks

src/config/default.json
- increased gas limit for farm position creator with single token
- N/A
=> [MEX-443] Update gas limits for farm single token position

src/modules/escrow/escrow.resolver.ts, src/modules/escrow/services/escrow.transaction.service.ts, src/modules/escrow/specs/escrow.transaction.service.spec.ts
- revert withdraw escrow transaction
- removed logic to check attributes on withdraw escrow transaction
- N/A
=> [SERVICES-2035] revert back withdraw escrow transaction

src/config/default.json
- update gas limits for swap enable
- N/A
=> [config] update gas limits for swap enable

src/main.ts
- HTTP error 413: payload too big
- increase accepted body parser payload to 1mb
- N/A
=> [SERVICES-2204] increase post body limit to 1mb

src/services/analytics/timescaledb/timescaledb.query.service.ts
- too many queries in timescaledb
- wrong values for series with timestamp < 24h
- remove the latest timestamp query from values24h query
- return only 24h window data from values24h query
- N/A
=> [SERVICES-2204] fix timescaledb query for 24h values

src/services/analytics/timescaledb/timescaledb.query.service.ts
- first value from 24h time samples is always `0`
- use the prev selector from locf function to search for latest value before the 24h window
- N/A
=> [SERVICES-2204] Fix first value from 24h time interval

src/config/mainnet.json, src/config/staging.json
- deployed new farm: TAO/EGLD farm
- added new farm for mainnet/staging config
- N/A
=> [config] add tao-egld farm for mainnet config

src/config/devnet.json
- migrate devnet setup to xExchange v3
- updated devnet config with new addresses for contracts
- N/A
=> [SERVICES-2247] new devnet setup for xExchange v3

src/config/default.json
- not enough gas on multi pair swap
- increase gas limit for multi pair swap multiplier
- N/A
=> [config] increase multi pair swap gas multiplier

src/config/mainnet.json, src/config/staging.json
- add metastaking option for BOBER/EGLD pairs with BOBER rewards
- added BOBER/EGLD farm address on mainnet & staging config
- N/A
=> [config] add BOBER/EGLD farm in mainnet and staging configs

src/modules/position-creator/services/position.creator.compute.ts
- missing denominated exchange rates for tokens
- add denominated values for tokens rate on position creator
- `tokenInExchangeRateDenom` field should be returned for any position creator single token query
=> [MEX-466]: add denominated values for tokens rate on position creator

src/modules/position-creator/services/position.creator.compute.ts
- missing fields from swap route model on position creator information
- added missing fields from swap route model
- N/A
=> [MEX-466] add missing swap information to position creator

src/modules/rabbitmq/handlers/pair.swap.handler.service.ts
- volumes for experimental and volatile tokens should be computed based on the quote token
- updated the computation for pairs volumes in USD value to use the quote token
- N/A
=> [SERVICES-2318] fix volumes compute in USD value

src/config/default.json, src/modules/router/specs/router.transactions.service.spec.ts
- lower gas limits for router transactions because of the gas increase fix on router contract
- updated the router transactions gas limits
- N/A
=> [config] update gas limits for mainnet

src/config/default.json
- not enough gas on multi pair swap transactions
- updated mulit pair swap gas limit multiplier
- N/A
=> [config] update gas limits

src/config/default.json, src/config/devnet.json, src/config/mainnet.json, src/config/staging.json
- add option to create pairs with MEX token
- updated configs for rounded swap enable with MEX token
- N/A
=> [SERVICES-2352] added MEX config for swap enable

src/services/analytics/timescaledb/timescaledb.query.service.ts
- return of latest complete values query is wrong
- fix the row column used for timestamp
- N/A
=> [SERVICES-2315] fix latest complete values query

src/modules/tokens/models/assets.interface.ts, src/modules/tokens/models/assets.model.ts, src/modules/tokens/token.module.ts, src/modules/tokens/token.resolver.ts
- missing token social links from assets
- added new social interface and model for token assets
- added new assets resolver
```
query Tokens {
tokens {
identifier
name
accounts
circulatingSupply
assets {
website
social {
email
blog
twitter
coinmarketcap
coingecko
}
}
}
}
```
- query should return values for token social if available from mx-assets
=> [SERVICES-2386]Token social links

src/modules/position-creator/position.creator.transaction.resolver.ts
- missing auth guard for position creator dual tokens transactions
- added auth guard for position creator dual tokens transactions
- N/A
=> [MEX-481] guard position creator dual tokens transactions

src/config/default.json, src/modules/position-creator/specs/position.creator.transaction.spec.ts
- updated gas limits for create energy position
- create energy position transaction with MEX should be successful
=> [MEX-480] update gas limits for create energy position

src/config/mainnet.json, src/config/staging.json
- new farm deployment
- added XOXNO farm address to config
- N/A
=> Add XOXNO farm config

src/config/default.json
- increased gas limit for stake farm tokens
- stake farm tokens with consolidation transaction should be successful
=> [MEX-480] update gas limit for stake farm tokens

src/config/shadowfork4.json
- new testing environment
- added new config for testing environment
- N/A
=> [MEX-470] added new config

src/config/default.json
- increased gas limit for farm position creator
- N/A
=> [MEX-480] Update gas limit for position creator

src/config/shadowfork4.json
- new contracts deployment
- updated smart contracts addresses for testing setup
- N/A
=> [MEX-470] update testing setup contracts addresses

src/modules/price-discovery/services/price.discovery.compute.service.ts, src/services/analytics/interfaces/analytics.query.interface.ts, src/services/analytics/mocks/analytics.query.service.mock.ts, src/services/analytics/services/analytics.query.service.ts, src/services/analytics/timescaledb/timescaledb.query.service.ts, src/services/crons/price.discovery.cache.warmer.service.ts
- improve resolve time for price discovery query
- used cached closing values for price discovery tokens prices
- removed unused analytics query for price discovery
- increased cron job execution interval for price discovery prices
- N/A
=> [MEX-493] price discovery query improvement

src/config/shadowfork2.json, src/modules/price-discovery/services/price.discovery.compute.service.ts
- new testing environment deployment
- added config for testing environment
- small fix on price discovery tokens prices
- N/A
=> [MEX-470] new testing environment

src/modules/tokens/services/token.compute.service.ts, src/modules/tokens/services/token.setter.service.ts, src/services/caching/cache.ttl.info.ts, src/services/crons/tokens.cache.warmer.service.ts
- reduce load on timescaledb instance
- execute queries performed in the tokens cache warmer in a sequential manner
- extend cache TTL
- N/A
=> [SERVICES-2529] Tokens cache warmer sequential timescaledb queries

src/config/shadowfork2.json
- new chainID used for battlenet network
- changed chainID for battlenet network
- N/A
=> [MEX-470] change chainID for battlenet environment

src/config/shadowfork2.json
- new setup for battlenet
- changed smart contracts addresses for battlenet env
- N/A
=> [MEX-470] sc deployments on battlenet

src/services/crons/logs.processor.service.ts
- no need to write information from battlenet env on db
- disable logs processor cron on battlenet env
- N/A
=> [MEX-470] disable logs processor on battlenet env

src/modules/escrow/services/escrow.abi.service.ts, src/services/cache.warmer.module.ts, src/services/crons/escrow.cache.warmer.service.ts
- poor performance on escrow related queries due to cache misses
- cache warm gateway response for escrow SC storage values
- N/A
=> [SERVICES-2534] Add escrow cache warmer

src/config/default.json
- increase gas limits for transactions
- N/A
=> [MEX-480] Update gas limits

src/modules/tokens/services/token.compute.service.ts
- token total value locked is fetched from timescaleDB based on last recored value
- compute token total value locked from pairs current reserves
- N/A
=> [MEX-499] token total value locked

src/modules/position-creator/position.creator.transaction.resolver.ts
- creating position with single token from lp tokens doesn't perform swaps
- check for lp token identifier payment in transaction resolver for single token position creators
```
query {
createDualFarmPositionSingleToken(
dualFarmAddress: <address>,
payment: {
tokenID: <lp_token_id>,
nonce: 0,
},
) {
transactions(
dualFarmAddress: <address>
) {
data
}
}
}
```
- query should return transaction for lp token id payment
=> [MEX-500] Fix create position single tokens with LP tokens

src/config/default.json
=> [MEX-480] gas limits update

src/services/analytics/timescaledb/timescaledb.query.service.ts
- first value from query is null
- use start of hour or start of day as start time for timescaleDB queries
- N/A
=> [MEX-497] fix time interval for timescaleDB queries

src/modules/farm/v2/services/farm.v2.compute.service.ts, src/modules/farm/v2/services/interfaces.ts, src/modules/fees-collector/services/fees-collector.compute.service.ts, src/modules/staking/services/staking.compute.service.ts, src/modules/user/user.info-by-week.resolver.ts, src/submodules/weekly-rewards-splitting/services/weekly-rewards-splitting.abi.service.ts, src/submodules/weekly-rewards-splitting/services/weekly-rewards-splitting.compute.service.ts
- outdated user information after claim rewards transaction is performed
- removed caches related to user information for energy rewards
- N/A
=> [MEX-504] user weekly rewards cache

src/modules/energy/services/energy.abi.service.ts, src/modules/user/services/userEnergy/user.energy.compute.service.ts, src/submodules/weekly-rewards-splitting/services/weekly-rewards-splitting.abi.service.ts
- fees rewards are not refreshed after claim transaction
- removed caching for user last active week
- N/A
=> [MEX-504] remove caching for user last active week

src/config/shadowfork2.json
- battlenet chain reset
- updated contracts on battlenet config
- N/A
=> [MEX-470] update contracts addresses on battlenet config

src/modules/tokens/services/token.loader.ts, src/modules/tokens/services/token.service.ts, src/modules/tokens/token.module.ts, src/modules/tokens/token.resolver.ts
- graphql field resolvers would trigger a get from cache for same base key
- improve getting batch of keys from caching
- added dataloader for token service
- N/A
=> [MEX-510] Tokens data loader

src/modules/pair/models/pair.model.ts, src/modules/pair/pair.module.ts, src/modules/pair/pair.resolver.ts, src/modules/pair/services/pair.abi.loader.ts, src/modules/pair/services/pair.compute.loader.ts, src/modules/pair/services/pair.service.ts, src/utils/get.many.utils.ts
- graphql field resolvers would trigger a get from cache for same base key
- improve getting batch of keys from caching
- added dataloader for pair abi service
- added dataloader for pair compute services
- N/A
=> [MEX-511] Pair data loader

src/modules/farm/base-module/farm.resolver.ts, src/modules/farm/base-module/services/farm.compute.loader.ts, src/modules/farm/base-module/services/farm.compute.service.ts, src/modules/farm/base-module/services/farm.setter.service.ts, src/modules/farm/base-module/services/interfaces.ts, src/modules/farm/mocks/farm.compute.service.mock.ts, src/modules/pair/services/pair.compute.service.ts, src/modules/router/services/router.service.ts, src/modules/token-unstake/services/token.unstake.abi.service.ts, src/modules/tokens/services/token.service.ts, src/modules/tokens/services/token.setter.service.ts, src/services/caching/cache.ttl.info.ts, src/services/crons/farm.cache.warmer.service.ts, src/services/crons/pair.cache.warmer.service.ts, src/services/crons/tokens.cache.warmer.service.ts
- missing cache warmed values from multiple modules
- same values cached with different keys
- cache TTL doesn't match with cron jobs intervals and keys expired before refresh
- added more keys to cache warmer cron jobs
- removed duplicated cached values
- updated caching TTLs
- N/A
=> [MEX-512] Caching improvements

src/config/default.json, src/modules/fees-collector/specs/fees-collector.transaction.service.spec.ts, src/modules/position-creator/services/position.creator.transaction.ts, src/modules/position-creator/specs/position.creator.transaction.spec.ts
- not enough gas on transactions
- updated gas limits for some transactions
- added dynamic gas computation for position creator transactions
- N/A
=> [MEX-480] gas configs update

src/modules/tokens/services/token.compute.service.ts, src/modules/tokens/services/token.service.ts, src/modules/tokens/specs/token.service.spec.ts, src/services/crons/pair.cache.warmer.service.ts
- missing type on LP token ESDT model
- missing price for LP token
- added type for LP tokens
- added compute price for LP token
- N/A
=> [MEX-513] Add LP token type

src/utils/get.many.utils.ts
- set local cache should not cache null values
- use parsed cached remote value to set the local cache
- N/A
=> [SERVICES-2582] fix set local cache

src/config/mainnet.json, src/config/staging.json
- deployed position creator, locked position creator and composable tasks addresses
- added position creator, locked position creator and composable tasks addresses
- N/A
=> [MEX-472] Update mainnet and staging config files

src/config/default.json
=> [MEX-480] update gas limit for staking unbond

src/utils/query.metrics.plugin.ts
- Currently, in cases where operationName is not, a SHA-256 hash is used for metrics. This completely hides the underlying queries
- Extract the schema query names from the document exposed on `GraphQLRequestContext` inside the metrics plugin
- N/A
=> [SERVICES-2588] Deanonymize query in metrics plugin

src/config/devnet.json
- new contracts deployed on devnet
- updated devnet config with new contracts addresses
- N/A
=> [MEX-470]: update devnet smart contracts setup

src/config/default.json
- updated gas limit for staking compound transaction
- N/A
=> [MEX-480] update gas limit for staking compound

src/modules/pair/pair.resolver.ts, src/modules/pair/services/pair.transactions.service.ts, src/modules/pair/specs/pair.transactions.service.spec.ts, src/services/multiversx-communication/mx.proxy.service.ts
- use SmartContractTransactionsFactory for generating transactions for Pairs SC
- update pair transaction service methods
- add sender parameter where needed + update resolver methods
- fix unit tests
- N/A
=> [SERVICES-2618] Update transaction generation for Pairs SC

src/modules/auto-router/services/auto-router.transactions.service.ts, src/modules/auto-router/specs/auto-router.service.spec.ts, src/modules/composable-tasks/services/composable.tasks.transaction.ts, src/modules/composable-tasks/specs/composable.tasks.transaction.spec.ts, src/modules/pair/pair.resolver.ts, src/modules/pair/services/pair.transactions.service.ts, src/modules/pair/specs/pair.transactions.service.spec.ts, src/modules/position-creator/services/position.creator.transaction.ts, src/modules/router/router.resolver.ts, src/modules/router/services/router.transactions.service.ts, src/modules/router/specs/router.transactions.service.spec.ts, src/services/multiversx-communication/mx.proxy.service.ts
- use SmartContractTransactionsFactory for generating transactions for Position Creator SC
- update position creator transaction service methods
- N/A
=> [SERVICES-2613] Update transaction generation for Position Creator SC

src/modules/energy/energy.resolver.ts, src/modules/energy/services/energy.transaction.service.ts, src/modules/energy/specs/energy.transaction.service.spec.ts, src/services/multiversx-communication/mx.proxy.service.ts
- use SmartContractTransactionsFactory for generating transactions for Energy Factory SC
- update EnergyTransactionService methods
- remove transaction generation methods not present in the abi
- update resolver methods
- add unit tests
- N/A
=> [SERVICES-2630] Update transaction generation for Simple Lock Energy SC

src/modules/distribution/distribution.resolver.ts, src/modules/distribution/services/distribution.transactions.service.ts, src/modules/distribution/specs/distribution.transactions.service.spec.ts, src/modules/escrow/escrow.resolver.ts, src/modules/escrow/services/escrow.transaction.service.ts, src/modules/escrow/specs/escrow.transaction.service.spec.ts, src/modules/fees-collector/fees-collector.resolver.ts, src/modules/fees-collector/services/fees-collector.transaction.service.ts, src/modules/fees-collector/specs/fees-collector.transaction.service.spec.ts, src/modules/locked-token-wrapper/services/locked-token-wrapper.transaction.service.ts, src/modules/locked-token-wrapper/specs/locked.token.wrapper.transaction.service.spec.ts, src/modules/metabonding/metabonding.resolver.ts, src/modules/metabonding/services/metabonding.transactions.service.ts, src/modules/metabonding/specs/metabonding.transactions.service.spec.ts, src/modules/price-discovery/price.discovery.resolver.ts, src/modules/price-discovery/services/price.discovery.transactions.service.ts, src/modules/token-unstake/services/token.unstake.transaction.service.ts, src/modules/token-unstake/specs/token.unstake.transaction.service.spec.ts, src/modules/user/services/userEnergy/user.energy.transaction.service.ts, src/services/multiversx-communication/mx.proxy.service.ts
- use SmartContractTransactionsFactory for generating transactions for the following SCs :  Distribution, Escrow, Fees Collector, Locked Asset Token Wrapper, Metabonding, Price Discovery, Token Unstake, Energy Update
- update transaction generation methods
- fix unit tests where needed
- add sender parameter where needed + update resolver methods
- N/A
=> [SERVICES-2633] Finalize transaction generation updates for sdk-core v13

src/modules/farm/base-module/services/farm.transaction.service.ts, src/modules/farm/farm.transaction.resolver.ts, src/modules/farm/specs/farm.transactions.service.spec.ts, src/modules/farm/v1.2/services/farm.v1.2.transaction.service.ts, src/modules/farm/v1.3/services/farm.v1.3.transaction.service.ts, src/modules/farm/v2/services/farm.v2.transaction.service.ts, src/services/multiversx-communication/mx.proxy.service.ts
- use SmartContractTransactionsFactory for generating transactions for Farms SC
- update all farm transaction services (base, v1.2, v1.3, v2) methods
- add sender parameter where needed + update resolver methods
- fix unit tests
- N/A
=> [SERVICES-2621] Update transaction generation for Farms SC

src/modules/user/services/userEnergy/user.energy.transaction.service.ts
- second argument on `updateFarmsEnergyForUser` endpoint needs to be a variadic value
- wrap the farms addresses argument into a variadic value
```
query {
updateEnergy(
includeAllContracts: true
skipFeesCollector: false
) {
value
receiver
gasPrice
gasLimit
data
chainID
version
__typename
}
}
```
=> [MEX-523] Fix type on update farms energy for user transaction

src/config/default.json, src/modules/user/services/userEnergy/user.energy.transaction.service.ts
- use farms length to compute gas limit
- N/A
=> [MEX-523] fix update farm energy gas computation

src/config/devnet.json
- new smart contracts deployments on devnet
- new governance energy contract
- new farm contract
- N/A
=> [MEX-470] added new devnet contracts

src/config/default.json
- increase gas for proxy farm exit
- N/A
=> [MEX-532] update gas limits for proxy farm exit

src/config/mainnet.json, src/config/staging.json
- deployed 2 new farms: MEX/USDC and KWAK/EGLD
- updated mainnet and staging configs with new farms addresses
- N/A
=> [MEX-579] new farms deployments

src/config/mainnet.json, src/config/staging.json
- farm deployment for FOXY/EGLD pair
- added FOXY/EGLD farm address to mainnet config
- N/A
=> [MEX-579] Add FOXY/EGLD farm address on mainnet config

src/config/default.json
- increased gas limit config for energy SC early unlock methods
- N/A
=> [MEX-655] increase gas limit for xMEX early unlock

src/modules/rabbitmq/handlers/pair.swap.handler.service.ts
- failed to start events notifier container
- added forward reference for dependent services
- N/A
=> [SERVICES-2603] fix service injection in swapEventHandler

src/public.app.module.ts
- `deprecationLoggerMiddleware` is causing performance degradation
- remove field middleware
- N/A
=> [MEX-656] Disable deprecation logger middleware

src/config/default.json
- updated gas limit for early unlock config
- N/A
=> [MEX-692] Increase gas limit for earlyUnlock tx

src/config/mainnet.json, src/config/staging.json
- added EGLD/USH farm
- added USH for common token
- updated mainnet & staging configs
- N/A
=> [MEX-714] add USH configs

src/modules/auto-router/services/auto-router.compute.service.ts
- excessive logging when computing best swap route
- remove log
- N/A
=> [MEX-717] Remove logging from best swap route compute

src/config/mainnet.json, src/config/staging.json
- new farm deployment
- added MEX-USH farm address for mainnet and staging configs
- N/A
=> [MEX-724] added MEX-USH farm address

src/modules/analytics/services/global.rewards.service.ts, src/modules/fees-collector/services/fees-collector.compute.service.ts
- globalRewards query doesn't return any feesCollectorRewards for the currentWeek
- Compute and return the accumulated feesCollector Rewards
```
query {
globalRewards (weekOffset: 0) {
feesCollectorGlobalRewards {
__typename
totalRewardsUSD,
energyRewardsUSD,
}
}
}
```
=> [MEX-730] Fixed FeesCollectorRewards for the currentWeek

src/modules/smart-router-evaluation/services/smart.router.evaluation.cron.ts
- the current implementation causes a valid swap to be deleted by a cron running in a different cluster
- ensure the mongodb document id is different before deleting a swap route
- N/A
=> [MEX-774] Fix race condition in smart router evaluation cron 

src/modules/push-notifications/crons/push.notifications.energy.ts, src/services/elastic-search/services/es.accounts.energy.service.ts
- Insufficient logs for the push notifications service
- Added extra logs and error handling for ES query
- N/A
=> [MEX-748] Added extra logs and try catch for ES query

src/config/default.json
- increased gas limit for stake farm transactions
- N/A
=> [MEX-692] increase gas limit

src/main.ts, src/modules/push-notifications/crons/push.notifications.energy.ts, src/modules/push-notifications/models/push.notifications.types.ts, src/modules/push-notifications/push.notifications.controller.ts, src/modules/push-notifications/push.notifications.cron.module.ts, src/modules/push-notifications/push.notifications.module.ts, src/modules/push-notifications/services/push.notifications.energy.service.ts, src/private.app.module.ts
- No way to trigger manually the feesCollectorRewardsCron if it fails
- Create an endpoint to manually trigger the cron
```
curl --location --request POST 'http://localhost:4001/push-notifications/fees-collector-rewards' \
--header 'Accept: application/json, text/plain, */*' 
```
=> [MEX-802] Manually Trigger feesCollectorRewards push notification

src/config/default.json, src/modules/auto-router/services/auto-router.service.ts, src/modules/remote-config/args/settings.args.ts, src/modules/remote-config/models/settings.model.ts, src/modules/remote-config/remote-config.controller.ts, src/modules/remote-config/remote-config.getter.service.ts, src/modules/remote-config/remote-config.module.ts, src/modules/remote-config/schemas/settings.schema.ts, src/services/database/repositories/settings.repository.ts
- MIN_SMART_SWAP_DELTA_PERCENTAGE config can't be changed without a redeployment
- moved the config to mongodb so that it can be changed while the service is running
- N/A
=> [MEX-775] Move config to mongodb

src/modules/trading-contest/services/trading.contest.swap.handler.service.ts
- there is currently no way to skip indexing for intermediary swaps
- skip indexing for swaps having the router SC as a caller if the `pairAddresses` field of a contest does not contain addresses
- N/A
=> [MEX-842] Ability to exclude intermediary swaps

src/config/default.json, src/modules/energy/services/energy.transaction.service.ts, src/modules/energy/specs/energy.transaction.service.spec.ts, src/modules/farm/v2/services/farm.v2.transaction.service.ts
- mismatch gas limits on specific transactions
- updated gas limits on specific transactions
- N/A
=> [MEX-692] update gas limits for specific transactions
